import add_picks

add_picks.CHECKED = "2026-10-05"


def r(user, name, best_for, title, rating, reviews, price, path, why, watch_out=""):
    return dict(user=user, name=name, best_for=best_for, title=title, rating=rating, reviews=reviews,
                level="Vetted Pro", price=price, url=path, why=why, watch_out=watch_out)


add_picks.put("video-animation/spokesperson-videos", [
    r("alliemadison12", "Allison", "Best overall for a promotional spokesperson video", "I will make a promotional spokesperson video", "5.0", "1000", "150",
      "/alliemadison12/make-a-video-about-what-interests-me",
      "A Vetted Pro with a perfect rating across more than a thousand reviews who films promotional spokesperson videos."),
    r("voiceoverbyluis", "Luis", "Best for English or Spanish spokesperson videos", "I will be your English or Spanish video spokesperson", "5.0", "1000", "100",
      "/voiceoverbyluis/your-bilingual-video-spokesperson",
      "A Vetted Pro with a perfect rating across more than a thousand reviews who presents on camera in English or Spanish."),
    r("bookreviewstew", "Mj Wolfe", "Best for a short green screen video", "I will be your video spokesperson on a green screen", "5.0", "1000", "175",
      "/bookreviewstew/shoot-a-20-word-video-on-a-green-screen-for-your-website-product-or-service",
      "A Vetted Pro with a perfect rating across more than a thousand reviews who films short green screen spokesperson videos."),
    r("faulksdigital", "Josh Faulks", "Best for saying your script on camera", "I will create a stunning spokesperson video for you", "5.0", "674", "145",
      "/faulksdigital/record-whatever-you-want-me-to-say-on-camera",
      "A Vetted Pro with a perfect rating across 674 reviews who records spokesperson videos from your script."),
    r("radevradostin", "Radostin Radev", "Best for being the face of your brand", "I will create an exceptional actor and spokesperson video for you", "5.0", "531", "115",
      "/radevradostin/be-the-face-of-your-brand-on-video",
      "A Vetted Pro with a perfect rating across 531 reviews who acts as an on-camera spokesperson for brands."),
    r("mlvoiceover", "Marshall", "Best for a fast male spokesperson video", "I will be your male spokesperson video actor", "5.0", "364", "225",
      "/mlvoiceover/create-an-attractive-spokesperson-video-in-48-hours-or-less",
      "A Vetted Pro with a perfect rating across 364 reviews who produces male spokesperson videos quickly."),
], status="live")

add_picks.put("online-marketing/brand-strategy", [
    r("ambermeadows", "Amber Johnson", "Best for a brand story", "I will create your brand story", "4.9", "353", "100",
      "/ambermeadows/create-your-brand-story",
      "A Vetted Pro with 353 reviews who writes brand stories, at a low starting price."),
    r("kristiek", "Kristie Keever", "Best for brand and marketing strategy advice", "I will be your brand and marketing strategy consultant", "4.9", "337", "100",
      "/kristiek/consult-with-you-on-your-branding-and-brand-strategy",
      "A Vetted Pro with 337 reviews who consults on branding and brand strategy."),
    r("tommysiu", "Chief", "Best for a brand name, slogan and strategy", "We will create a winning brand name, slogan and strategy for you", "4.9", "306", "250",
      "/tommysiu/develop-a-powerful-brand-name-slogan-and-strategy-for-you",
      "A Vetted Pro agency with 306 reviews that develops brand names, slogans and strategy together."),
    r("sally_gale", "Sally", "Best for defining a brand's style and story", "I will define your brand strategy", "4.9", "193", "200",
      "/sally_gale/articulate-your-brands-style-and-story",
      "A Vetted Pro with 193 reviews who defines brand strategy, style and story."),
    r("jormaryarbelaez", "Mary Arbelaez", "Best for brand voice and personality", "I will create your brand strategy for your business", "4.9", "127", "195",
      "/jormaryarbelaez/write-brand-voice-to-define-your-brand-personality",
      "A Vetted Pro with 127 reviews who defines brand voice and personality as part of brand strategy."),
    r("omarsinbawy", "Omar S", "Best for a branding consultation", "I will consult you on your brand strategy and branding", "4.9", "63", "150",
      "/omarsinbawy/consult-you-on-your-brand-strategy-and-branding",
      "A Vetted Pro who consults on brand strategy and branding."),
], status="live")

add_picks.put("online-marketing/digital-marketing-strategy", [
    r("blivmarketing", "Liv", "Best budget pick for a growth-focused marketing plan", "I will develop your marketing plan to grow sales", "5.0", "70", "100",
      "/blivmarketing/develop-a-robust-marketing-strategy-for-your-brand",
      "A Vetted Pro with a perfect rating who develops marketing strategies aimed at growing sales, at a low starting price."),
    r("kesosanikidze", "Keso S.", "Best for an integrated plan with ongoing support", "I will create a marketing strategy and growth plan with a 3-month retainer", "4.9", "227", "100",
      "/kesosanikidze/create-an-integrated-marketing-plan-for-your-business",
      "A Vetted Pro with 227 reviews who creates integrated marketing plans for businesses."),
    r("holly_michael", "Holly Michael", "Best for content marketing strategy advice", "I will provide content marketing strategy advice", "4.9", "55", "100",
      "/holly_michael/provide-content-marketing-strategy-advice",
      "A Vetted Pro who gives advice on content marketing strategy."),
    r("nadyarousseau", "Nadya R", "Best for brand and digital strategy together", "I will help you develop your brand and digital marketing strategies", "4.8", "175", "450",
      "/nadyarousseau/help-you-develop-your-digital-marketing-strategy",
      "A Vetted Pro with 175 reviews who builds brand and digital marketing strategies.",
      "Starts at 450 dollars."),
    r("evomediauk", "Steven Wilson", "Best for a digital marketing consultation", "I will provide a digital marketing consultation", "4.8", "93", "200",
      "/evomediauk/be-your-digital-marketing-consultant",
      "A Vetted Pro with 93 reviews who provides digital marketing consultations."),
], status="live")

add_picks.put("online-marketing/conversion-rate-optimization-cro", [
    r("alexiscottray", "Alexis C", "Best for a video UX audit aimed at conversions", "I will audit B2B and B2C SaaS websites to improve conversions", "5.0", "125", "150",
      "/alexiscottray/perform-a-video-on-screen-ux-ui-audit-for-cro",
      "A Vetted Pro with a perfect rating across 125 reviews who audits websites for conversion problems and records the findings on video."),
    r("giovanni_ux", "Giovanni", "Best for a CRO audit of a whole website", "I will do a CRO audit of your website to increase conversion", "5.0", "99", "245",
      "/giovanni_ux/perform-a-professional-digital-audit",
      "A Vetted Pro with a perfect rating who audits websites to find ways to increase conversion."),
    r("teodorulmanen", "Teodor U", "Best budget pick for a Shopify CRO audit", "I will write an expert Shopify CRO audit to increase your conversion rate", "5.0", "76", "100",
      "/teodorulmanen/audit-your-website-to-maximize-conversions",
      "A Vetted Pro with a perfect rating who writes conversion audits for online stores, at a low starting price."),
    r("vinhly1", "Vinh", "Best for improving website conversion rates", "I will dramatically improve your website conversion rate", "4.9", "1000", "100",
      "/vinhly1/dramatically-improve-your-conversion-rates",
      "A Vetted Pro with more than a thousand reviews who works on website conversion rate optimization."),
    r("brndoil96", "Ildebrando", "Best for lifting a Shopify store's conversion rate", "I will increase the conversion rate of your Shopify store", "4.9", "328", "200",
      "/brndoil96/get-your-shopify-store-more-sales-by-increasing-your-conversion-rate",
      "A Vetted Pro with 328 reviews who audits and improves conversion rates for Shopify stores."),
    r("jidesigns", "Just Create It", "Best for a Shopify CRO audit from an agency", "We will do a Shopify CRO audit or conversion rate optimization", "4.9", "218", "100",
      "/jidesigns/audit-your-shopify-website-or-drop-shipping-site-to-convert-better",
      "A Vetted Pro agency with 218 reviews that audits Shopify and dropshipping sites for conversion."),
], status="live")

add_picks.put("online-marketing/web-analytics", [
    r("ah_sajib", "Afjal Hossain S", "Best overall for pixel and analytics setup", "I will fix or set up Facebook Pixel and Google Analytics 4", "5.0", "1000", "100",
      "/ah_sajib/setup-facebook-pixel-catalog-events-custom-audience-and-google-analytics",
      "A Vetted Pro with a perfect rating across more than a thousand reviews who sets up Facebook Pixel and Google Analytics 4."),
    r("chrismccreery", "Chris McCreery", "Best for analytics, Tag Manager and conversion pixels", "I will provide Google Analytics, Tag Manager and conversion pixel installation", "5.0", "188", "125",
      "/chrismccreery/install-google-analytics-and-optimize",
      "A Vetted Pro with a perfect rating across 188 reviews who installs and tunes Google Analytics, Tag Manager and conversion pixels."),
    r("attilio10", "Attilio C.", "Best for a GA4 setup", "I will set up Google Analytics 4 (GA4)", "5.0", "82", "295",
      "/attilio10/configurer-votre-google-analytics-4",
      "A Vetted Pro with a perfect rating who sets up Google Analytics 4."),
    r("sudiptosalehin", "Sudipto Salehin", "Best budget pick for Pixel and GA4 installation", "I will install Facebook Pixel and Google Analytics 4 on your website", "4.9", "983", "100",
      "/sudiptosalehin/install-google-analytics-and-facebook-pixel-in-your-website",
      "A Vetted Pro with 983 reviews who installs Facebook Pixel and Google Analytics 4, at a low starting price."),
    r("weswalker281", "Wesley Walker", "Best for Google Analytics consulting", "I will provide Google Analytics consultations", "4.9", "62", "100",
      "/weswalker281/provide-google-analytics-consultancy",
      "A Vetted Pro with 62 reviews who gives Google Analytics consultations."),
    r("josswalle", "Josipher Walle", "Best for GA4 on an online store", "I will set up Google Analytics 4 for e-commerce so it makes sense", "4.9", "54", "100",
      "/josswalle/set-up-google-analytics-4",
      "A Vetted Pro who sets up Google Analytics 4 for e-commerce sites."),
], status="live")

add_picks.put("business/market-research", [
    r("rahul2111", "Rahul C", "Best overall for comprehensive market research", "I will do a comprehensive market research for your business", "5.0", "652", "245",
      "/rahul2111/do-market-research-for-any-product",
      "A Vetted Pro with a perfect rating across 652 reviews who does market research for any product."),
    r("loaloariad", "Dr. Loaloa Riad", "Best for validating a business idea", "I will validate your business idea with strategic market research", "4.9", "472", "195",
      "/loaloariad/provide-a-market-research-for-your-products",
      "A Vetted Pro with 472 reviews who validates business ideas with market research."),
    r("jormaryarbelaez", "Mary Arbelaez", "Best for market research with buyer personas", "I will do market research and a buyer persona for your brand or idea", "4.9", "736", "165",
      "/jormaryarbelaez/create-ideal-buyer-persona-for-your-business",
      "A Vetted Pro with 736 reviews who combines market research with buyer personas."),
    r("naveen_kala", "Naveen Kala", "Best for industry reports and company profiles", "I will perform market research, industry reports and company profiling", "4.9", "261", "120",
      "/naveen_kala/perform-market-research-industry-report-company-profiling",
      "A Vetted Pro with 261 reviews who writes industry reports and company profiles."),
    r("dikovh", "Hristo Dikov", "Best for in-depth research on a business", "I will do professional market research for your business", "4.9", "239", "400",
      "/dikovh/do-professional-market-research-for-your-business",
      "A Vetted Pro with 239 reviews who does professional market research for businesses.",
      "Starts at 400 dollars."),
    r("fahadahmed921", "Fahad A", "Best budget pick for any industry", "I will do strategic market research to validate your business idea", "4.8", "283", "100",
      "/fahadahmed921/provide-a-professional-market-research-for-any-industry",
      "A Vetted Pro with 283 reviews who does market research across industries, at a low starting price."),
], status="live")

add_picks.put("video-animation/visual-effects", [
    r("sahilhaider", "Saahil H.", "Best overall for VFX compositing", "I will do VFX compositing for filmmakers and short films", "5.0", "987", "135",
      "/sahilhaider/add-professional-vfx-to-your-video-in-12-hours",
      "A Vetted Pro with a perfect rating across 987 reviews who adds VFX and compositing to films and videos."),
    r("karam10", "VFXaddART", "Best for a full VFX, color and compositing agency", "We will do VFX, compositing, animation and cleanup", "5.0", "282", "750",
      "/karam10/do-professional-vfx-editing-color-grading-compositing",
      "A Vetted Pro agency with a perfect rating across 282 reviews that handles VFX, color grading and compositing.",
      "Starts at 750 dollars."),
    r("cutornot", "Aleksa M", "Best budget pick for all kinds of effects", "I will be your professional visual effects artist", "5.0", "109", "100",
      "/cutornot/make-all-kinds-of-visual-effects-for-you",
      "A Vetted Pro with a perfect rating who creates many kinds of visual effects, at a low starting price."),
    r("gyulakunsagi", "Gyula", "Best for custom VFX and CGI", "I will do custom VFX and CGI", "5.0", "105", "300",
      "/gyulakunsagi/do-custom-vfx-cgi",
      "A Vetted Pro with a perfect rating who creates custom VFX and CGI."),
    r("shakilsky9", "Shakil", "Best for film-style effects at a low price", "I will edit your video or film with near Hollywood-level effects", "4.9", "437", "100",
      "/shakilsky9/edit-your-video-or-film-near-hollywood-level-effects",
      "A Vetted Pro with 437 reviews who adds film-style VFX to videos, at a low starting price."),
    r("zproduction", "Serhiy P", "Best for compositing your shots", "I will do professional VFX compositing for your shots", "4.9", "161", "150",
      "/zproduction/do-compositing-for-your-shots",
      "A Vetted Pro with 161 reviews who does VFX compositing for film and video shots."),
], status="live")
