import add_picks

add_picks.CHECKED = "2026-10-04"


def r(user, name, best_for, title, rating, reviews, price, url, why, watch_out=""):
    return dict(user=user, name=name, best_for=best_for, title=title, rating=rating, reviews=reviews,
                level="Vetted Pro", price=price, url=url, why=why, watch_out=watch_out)


add_picks.put("music-audio/audiobook-production", [
    r("benhauck", "Ben Hauck Voice", "Best overall for narration to ACX standards", "I will narrate your Audible audiobook to ACX standards", "5.0", "134", "200",
      "/benhauck/asap-record-an-audible-audiobook-to-acx-standards",
      "A Vetted Pro with a perfect rating across 134 reviews who narrates audiobooks to ACX standards."),
    r("jon_lobb", "Jon", "Best for narration, editing and production", "I will narrate, edit and produce your Audible audiobook to ACX standards", "5.0", "77", "175",
      "/jon_lobb/narrate-an-audiobook-to-acx-standards",
      "A Vetted Pro with a perfect rating who narrates, edits and produces audiobooks to ACX standards."),
    r("auditorii", "Torii A.", "Best budget pick for narration and production", "I will narrate and produce your audiobook to ACX Audible specification", "5.0", "65", "100",
      "/auditorii/bring-your-audiobook-to-life",
      "A Vetted Pro with a perfect rating who narrates and produces audiobooks to ACX specification, at a low starting price."),
    r("tro2789", "Trevor O", "Best for narration plus editing", "I will be your audiobook narrator and editor for ACX, Audible and iTunes", "4.9", "92", "100",
      "/tro2789/record-an-audiobook-for-acx",
      "A Vetted Pro with 92 reviews who narrates and edits audiobooks for ACX, Audible and iTunes."),
    r("stephendaltonvo", "Stephen Dalton", "Best for Irish, British or American narration", "I will be an Irish, British or American audiobook narrator", "4.9", "108", "500",
      "/stephendaltonvo/voice-edit-and-produce-your-audiobook",
      "A Vetted Pro with 108 reviews who narrates, edits and produces audiobooks in Irish, British or American English.",
      "Starts at 500 dollars."),
], status="live")

add_picks.put("music-audio/jingles-and-intros", [
    r("noaniemusic", "Noanie Music", "Best for a full-quality jingle in any genre", "I will produce a pro-quality jingle in any genre", "5.0", "634", "995",
      "/noaniemusic/we-will-write-produce-sing-a-super-catchy-jingle-for-you",
      "A Vetted Pro with a perfect rating across 634 reviews who writes, produces and sings jingles in any genre.",
      "Premium pricing, starting near 995 dollars."),
    r("edbishopvo", "Ed Bishop", "Best budget pick for a podcast intro", "I will produce a custom podcast intro with music and voiceover", "5.0", "149", "100",
      "/edbishopvo/provide-voiceover-and-produce-your-podcast-intros-and-outros",
      "A Vetted Pro with a perfect rating across 149 reviews who produces podcast intros and outros with music and voiceover, at a low starting price."),
    r("adamblotner", "Adam B", "Best for funny or catchy jingles", "I will produce a funny theme song or jingle", "5.0", "207", "295",
      "/adamblotner/write-and-record-a-comedic-song",
      "A Vetted Pro with a perfect rating across 207 reviews who writes and records funny theme songs and jingles."),
    r("damooch916", "Tommy J", "Best for podcast and theme music", "I will create an amazing theme or podcast music", "5.0", "82", "200",
      "/damooch916/create-a-podcast-theme-or-backing-theme-song-and-more",
      "A Vetted Pro with a perfect rating who creates podcast themes and backing theme songs."),
    r("nicolecarino", "Nicole Carino", "Best for recorded jingles and ads", "I will record your jingle, advertisement, theme song or intro", "4.9", "275", "100",
      "/nicolecarino/be-your-songwriter-pop-edm-country-rock-urban-gospel",
      "A Vetted Pro with 275 reviews who records jingles, advertisements, theme songs and intros, at a low starting price."),
], status="live")

add_picks.put("graphics-design/book-design", [
    r("benayoubdz", "BenCreatesBooks", "Best for KDP and print formatting", "Our agency will format your book for Amazon KDP, IngramSpark and print", "5.0", "116", "550",
      "/benayoubdz/do-ebook-conversion-from-ms-word-into-epub-and-kindle-formats",
      "A Vetted Pro agency with a perfect rating across 116 reviews that formats books for Amazon KDP, IngramSpark and print.",
      "Starts at 550 dollars."),
    r("brandondanie982", "Brandon Daniel", "Best for complete book design with a cover", "I will design any book expertly for print PDF and ebook with a cover", "5.0", "186", "225",
      "/brandondanie982/transform-your-text-into-a-beautiful-book",
      "A Vetted Pro with a perfect rating across 186 reviews who designs books for print PDF and ebook, with a cover."),
    r("aimasterdesign", "Sienna Arts", "Best budget pick for novel interiors", "I will format a beautiful book interior for KDP, IngramSpark, EPUB and PDF", "4.9", "231", "100",
      "/aimasterdesign/format-beautiful-novel-interior-book-for-kdp-or-ingram-epub-pdf-mobi",
      "A Vetted Pro with 231 reviews who formats book interiors for KDP and IngramSpark and as EPUB and PDF, at a low starting price."),
    r("mikymikymiky", "Miky R.", "Best for formatting, cover and upload help", "I will do book and ebook formatting, cover design and upload your book to Amazon", "4.9", "400", "390",
      "/mikymikymiky/convert-and-format-your-book-to-amazon-standards",
      "A Vetted Pro with 400 reviews who formats books and ebooks to Amazon standards and helps with cover design and upload."),
    r("marmarko78", "Marko M.", "Best for ebook and print layout", "I will do ebook formatting and layout design for Kindle, print PDF and KDP", "4.9", "85", "375",
      "/marmarko78/format-your-book-for-createspace-ingram-spark-kdp-kindle-or-ebook",
      "A Vetted Pro with 85 reviews who does ebook formatting and layout design for Kindle and print."),
    r("hmdgfx", "HMD Publishing", "Most reviewed for formatting and publishing", "Our agency will do book formatting, layout design and typesetting for KDP", "4.8", "1000", "185",
      "/hmdgfx/help-you-to-format-and-publish-your-book",
      "A Vetted Pro agency with more than a thousand reviews that does book formatting, layout design and typesetting for KDP."),
], status="live")

add_picks.put("graphics-design/childrens-book-illustration", [
    r("otido4u", "Kateryna Ch", "Best overall for story illustrations and covers", "I will draw unique children's book illustrations and covers", "5.0", "334", "150",
      "/otido4u/draw-children-story-book-illustration-for-you",
      "A Vetted Pro with a perfect rating across 334 reviews who draws children's book illustrations and covers."),
    r("irabaykovska", "Ira B.", "Best for children's book illustration", "I will draw awesome children's book illustration", "5.0", "307", "110",
      "/irabaykovska/do-illustration-of-anything",
      "A Vetted Pro with a perfect rating across 307 reviews who draws children's book illustrations, at a low starting price."),
    r("byqoni", "Qoni Fadhilah", "Best for whimsical characters", "I will draw your unique and whimsical children's book illustration", "5.0", "80", "100",
      "/byqoni/draw-your-unique-child-book-character-illustration",
      "A Vetted Pro with a perfect rating who draws whimsical children's book characters and illustrations."),
    r("hameoart", "Hameo Pham", "Best budget pick for a children's book", "I will illustrate your children's book", "5.0", "72", "100",
      "/hameoart/create-beautiful-children-book-illustration",
      "A Vetted Pro with a perfect rating who illustrates children's books, at a low starting price."),
    r("sonaandjacob", "Jacob N", "Most reviewed for children's illustrations", "I will create exceptional children's book illustrations", "4.9", "571", "100",
      "/sonaandjacob/create-excellent-childrens-book-illustrations",
      "A Vetted Pro with 571 reviews who creates children's book illustrations."),
    r("girlvsworld", "Annie W", "Best for beautiful story illustrations", "I will create beautiful illustrations for your children's book", "4.9", "142", "100",
      "/girlvsworld/create-beautiful-illustrations-for-your-childrens-book-59b9",
      "A Vetted Pro with 142 reviews who creates illustrations for children's books."),
], status="live")

add_picks.put("video-animation/3d-product-animation", [
    r("daniel_3d", "Daniel M", "Best overall for modeling and animation", "I will do 3D product animation", "5.0", "327", "400",
      "/daniel_3d/do-3d-modeling-including-texture-rig-animation-and-render",
      "A Vetted Pro with a perfect rating across 327 reviews who does 3D modeling, texturing, rigging, animation and rendering."),
    r("ben_vitagliano", "Ben", "Best budget pick for photorealistic renders", "I will do photorealistic 3D product rendering and animation", "5.0", "181", "100",
      "/ben_vitagliano/render-photorealistic-pictures-of-your-products",
      "A Vetted Pro with a perfect rating across 181 reviews who does photorealistic 3D product rendering and animation, at a low starting price."),
    r("iuriikharchenko", "Yuri", "Best for high-quality brand animation", "I will create high-quality 3D product animation for your brand", "5.0", "89", "600",
      "/iuriikharchenko/do-3d-product-animation",
      "A Vetted Pro with a perfect rating who creates high-quality 3D product animation for brands.",
      "Starts at 600 dollars."),
    r("renvyrere", "Renvy R", "Best for realistic product motion", "I will do realistic 3D product animation and motion", "5.0", "64", "350",
      "/renvyrere/do-3d-product-animation-and-modelling",
      "A Vetted Pro with a perfect rating who does realistic 3D product animation and modelling."),
    r("hiro_cbh", "Hiroshani K", "Most reviewed for 3D product animation", "I will do 3D product animation", "4.9", "540", "300",
      "/hiro_cbh/do-3d-product-animation",
      "A Vetted Pro with 540 reviews who does 3D product animation."),
    r("lorislibero", "Loris L.", "Best for photorealistic rendering and animation", "I will create photorealistic 3D product rendering and animation", "4.9", "307", "100",
      "/lorislibero/make-photorealistic-product-rendering-or-3d-animation",
      "A Vetted Pro with 307 reviews who creates photorealistic 3D product rendering and animation, at a low starting price."),
], status="live")

add_picks.put("graphics-design/cartoon-illustration", [
    r("lucianolabate", "Luciano L.", "Best overall for characters and mascots", "I will draw an amusing illustration, cartoon character or mascot", "5.0", "440", "120",
      "/lucianolabate/im-really-good-at-illustrations",
      "A Vetted Pro with a perfect rating across 440 reviews who draws cartoon characters and mascots."),
    r("nextgirl91", "Ade P", "Best for anime-style characters", "I will draw an illustration of your character in cool anime style", "5.0", "206", "100",
      "/nextgirl91/draw-anime-or-your-original-characters-in-my-distinct-style",
      "A Vetted Pro with a perfect rating across 206 reviews who draws your character in an anime style."),
    r("billalger", "Bill A.", "Best for original cartoon vector characters", "I will create a fun original cartoon character vector illustration", "5.0", "166", "250",
      "/billalger/create-an-original-cartoon-vector-illustration",
      "A Vetted Pro with a perfect rating who creates original cartoon character vector illustrations."),
    r("slavkokahovsky", "Slavko Kahovsky", "Best for a unique, trippy cartoon style", "I will create custom cartoon illustration in my unique trippy style", "5.0", "165", "100",
      "/slavkokahovsky/create-digital-illustration-in-my-unique-cartoon-style",
      "A Vetted Pro with a perfect rating who creates custom cartoon illustration in a unique trippy style, at a low starting price."),
    r("ramialhakim", "RAMI", "Most reviewed for character illustration", "I will design professional character illustrations and vector illustrations", "4.9", "562", "100",
      "/ramialhakim/make-a-simple-cartoon-for-your-original-character",
      "A Vetted Pro with 562 reviews who designs character and vector illustrations."),
    r("oskardraws", "Oskar M", "Best for cartoon or manga characters", "I will draw characters in cartoon or anime style", "4.9", "115", "100",
      "/oskardraws/draw-you-in-cartoon-or-manga-style",
      "A Vetted Pro with 115 reviews who draws characters in cartoon or anime style."),
], status="live")

add_picks.put("graphics-design/portraits-and-caricatures", [
    r("elysios", "Elysios", "Best for a painted portrait without AI", "I will draw a professional portrait painting for you, no AI", "5.0", "129", "260",
      "/elysios/paint-you-a-vibrant-portrait",
      "A Vetted Pro with a perfect rating across 129 reviews who paints professional portraits without AI.",
      "Starts at 260 dollars."),
    r("sebadibujando", "Seba Guidobono", "Best for funny drawings from a photo", "I will draw and convert your photo into a funny drawing", "5.0", "92", "100",
      "/sebadibujando/convert-your-photo-in-a-funny-drawing-2e40",
      "A Vetted Pro with a perfect rating who turns your photo into a funny drawing, at a low starting price."),
    r("fahmin", "Fahmin Abdullah", "Best for realistic portrait painting", "I will do digital illustration, concept art and realistic portrait painting", "5.0", "67", "120",
      "/fahmin/do-digital-illustration-concept-art-and-realistic-portrait-painting",
      "A Vetted Pro with a perfect rating who does realistic portrait painting and digital illustration."),
    r("eleofanta", "Eleonora D", "Best for handmade watercolor portraits", "I will draw a handmade watercolor portrait", "5.0", "62", "100",
      "/eleofanta/draw-handmade-watercolor-portrait",
      "A Vetted Pro with a perfect rating who draws handmade watercolor portraits, at a low starting price."),
    r("liubov_rudenko", "Liuba R.", "Most reviewed for watercolor portraits", "I will draw an outstanding watercolor portrait", "4.9", "190", "145",
      "/liubov_rudenko/draw-your-watercolor-portrait",
      "A Vetted Pro with 190 reviews who draws watercolor portraits."),
    r("willnoname", "Wilfredo G", "Best for big-head caricatures", "I will draw a custom big-head caricature from your photo", "4.8", "66", "100",
      "/willnoname/draw-you-an-amazing-caricature-with-your-hobbie",
      "A Vetted Pro with 66 reviews who draws custom big-head caricatures from your photo, at a low starting price."),
], status="live")

add_picks.put("graphics-design/comic-illustration", [
    r("sebadibujando", "Seba Guidobono", "Best for comic character design", "I will draw and design your comic character", "5.0", "170", "100",
      "/sebadibujando/design-your-comic-character",
      "A Vetted Pro with a perfect rating across 170 reviews who draws and designs comic characters, at a low starting price."),
    r("adrianiglesias", "Adrian", "Best for comic character sheets and pages", "I will draw your comic character model sheet", "5.0", "133", "110",
      "/adrianiglesias/draw-a-amazing-comic-page-for-you",
      "A Vetted Pro with a perfect rating across 133 reviews who draws comic character model sheets and comic pages."),
    r("artmikegarcia", "Mike G.", "Best for a comic page from a script", "I will create a comic book page for your brand or story", "5.0", "107", "160",
      "/artmikegarcia/create-a-comic-page-based-on-your-script-cc35",
      "A Vetted Pro with a perfect rating who creates a comic page based on your script."),
    r("nextgirl91", "Ade P", "Best for manga-style black and white pages", "I will draw a black and white comic page with a manga style", "5.0", "99", "100",
      "/nextgirl91/draw-a-black-and-white-comic-page-with-my-style",
      "A Vetted Pro with a perfect rating who draws black and white comic pages in a manga style, at a low starting price."),
    r("novalhernawan", "Noval Hernawan", "Best for comic book covers", "I will draw an awesome comic book cover illustration", "5.0", "95", "150",
      "/novalhernawan/make-the-an-awesome-comic-book-cover-for-you",
      "A Vetted Pro with a perfect rating who draws comic book cover illustrations."),
], status="live")
