import add_picks

add_picks.CHECKED = "2026-10-04"


def r(user, name, best_for, title, rating, reviews, price, url, why, watch_out=""):
    return dict(user=user, name=name, best_for=best_for, title=title, rating=rating, reviews=reviews,
                level="Vetted Pro", price=price, url=url, why=why, watch_out=watch_out)


add_picks.put("video-animation/e-commerce-product-videos", [
    r("meowmau", "Mia Videos", "Best overall for product demo videos", "I will create a high-converting product video for Amazon and e-commerce", "5.0", "233", "120",
      "/meowmau/create-a-professional-product-demo-video",
      "A Vetted Pro with a perfect rating across 233 reviews who creates product demo videos for Amazon and online stores, at a low starting price."),
    r("mdadalauri", "Meli", "Best for premium 4K product video", "I will shoot premium Amazon product videos and social media ads", "5.0", "53", "250",
      "/mdadalauri/create-a-4k-amazon-product-video-for-your-product-d94f",
      "A Vetted Pro with a perfect rating who shoots 4K product videos and social media ads.",
      "Fewer reviews than others on this list, at 53."),
    r("ann_model", "Ann", "Best for lifestyle and unboxing videos", "I will create a 4K Amazon product video ad, lifestyle and unboxing", "4.9", "363", "175",
      "/ann_model/create-a-product-video-ad-for-amazon-etsy-shopify-or-dropshipping",
      "A Vetted Pro with 363 reviews who creates product video ads for Amazon, Etsy, Shopify and dropshipping stores."),
    r("mikevann", "Envy Creative", "Best agency pick for unboxing and review videos", "Our agency will make a product video for Amazon or e-commerce with real people", "4.9", "356", "150",
      "/mikevann/make-a-unboxing-and-review-video",
      "A Vetted Pro agency with 356 reviews that makes product, unboxing and review videos featuring real people."),
    r("nastiajanena", "Nastia J", "Best for baby product videos", "I will do a baby product video for Amazon", "4.9", "83", "300",
      "/nastiajanena/do-baby-product-video-for-amazon-etc",
      "A Vetted Pro with 83 reviews who specializes in baby product videos for Amazon and other stores.",
      "Specialized in baby products, so check the fit for other categories."),
    r("rafaelarossigno", "Rafaela Ross", "Best for short product ads", "I will create an Amazon and Facebook ads product video", "4.8", "50", "150",
      "/rafaelarossigno/create-short-video-ad-for-your-amazon-product-facebook-ads",
      "A Vetted Pro with 50 reviews who creates short product video ads for Amazon and Facebook.",
      "Fewer reviews than others on this list, at 50."),
], status="live")

add_picks.put("video-animation/character-animation", [
    r("alen_animation", "Alen", "Best for animating an existing 2D character", "I will rig and animate your existing 2D character", "5.0", "113", "160",
      "/alen_animation/vector-tracing-and-animate-your-2d-character-professionally",
      "A Vetted Pro with a perfect rating across 113 reviews who rigs and animates existing 2D characters."),
    r("shamod_chanuka", "Shamodc", "Best for stylized 3D characters", "I will animate stylized 3D characters for videos or games", "5.0", "84", "500",
      "/shamod_chanuka/do-3d-character-modeling-and-animation",
      "A Vetted Pro with a perfect rating who models and animates stylized 3D characters for videos and games.",
      "Starts at 500 dollars."),
    r("pierreschiller", "Pierre", "Best for 3D VFX character animation", "I will create animation with your 3D character", "5.0", "67", "1200",
      "/pierreschiller/create-3d-vfx-characters-and-animation",
      "A Vetted Pro with a perfect rating who animates 3D characters with VFX.",
      "Premium pricing, starting around 1,200 dollars."),
    r("cananpictures", "Canan Pictures", "Best for anime-style 2D animation", "I will create a traditional 2D animation in anime style", "4.9", "61", "500",
      "/cananpictures/do-2d-animation-as-your-request",
      "A Vetted Pro with 61 reviews who creates traditional 2D animation in anime style.",
      "Starts at 500 dollars."),
    r("sara_derbala", "Sara D", "Best budget pick for 2D character animation", "I will create professional 2D character animation", "4.8", "177", "100",
      "/sara_derbala/animate-any-2d-cartoon-character-animation-for-you",
      "A Vetted Pro with 177 reviews who animates 2D cartoon characters, at a low starting price."),
], status="live")

add_picks.put("graphics-design/game-art", [
    r("gamesmartist", "Antonio Pacheco", "Best for 2D game character design", "I will do a 2D character design and concept art for your game", "5.0", "88", "125",
      "/gamesmartist/do-a-professional-character-design-for-your-game",
      "A Vetted Pro with a perfect rating who does 2D character design and concept art for games."),
    r("davidch7", "David C.", "Best for game icons, sprites and UI", "I will design custom 2D game icons, assets, sprites, maps, HUDs and UI", "5.0", "107", "100",
      "/davidch7/create-a-2d-game-asset-icon-sprite-etc",
      "A Vetted Pro with a perfect rating across 107 reviews who designs 2D game assets, sprites, maps and UI, at a low starting price."),
    r("vitogh", "Joze G", "Best for scene illustration", "I will draw professional artwork for your game or book", "5.0", "54", "170",
      "/vitogh/illustrate-a-beautiful-scene-for-your-book-or-game",
      "A Vetted Pro with a perfect rating who draws scene artwork for games and books.",
      "Fewer reviews than others on this list, at 54."),
    r("dcworkartstudio", "Cakka", "Best for fantasy character concept art", "I will draw fantasy and D&D game character concept art, design and illustration", "4.9", "130", "165",
      "/dcworkartstudio/design-you-any-character",
      "A Vetted Pro with 130 reviews who draws fantasy and D&D character concept art."),
    r("kh_ashique", "Ashiqe", "Most reviewed for environment concept art", "I will create 3D or 2D sci-fi, fantasy or realistic environment concept art", "4.9", "327", "100",
      "/kh_ashique/create-3d-sci-fi-fantasy-or-realistic-environment-concept-art",
      "A Vetted Pro with 327 reviews who creates sci-fi, fantasy and realistic environment and character concept art, at a low starting price."),
    r("alejandrojamett", "Dreamerr Lab", "Best for environment concept art", "Our agency will make environment concept art for games, books and movies", "4.9", "85", "100",
      "/alejandrojamett/do-environment-concept-art",
      "A Vetted Pro agency with 85 reviews that makes environment concept art for games, books and films."),
], status="live")

add_picks.put("writing-translation/book-editing", [
    r("emma_moylan", "Emma Moylan", "Best for self-published books", "I will copy edit and proofread your book, ebook or novel", "5.0", "415", "100",
      "/emma_moylan/proofread-self-published-book-manuscript-proof-read-errors-fix-grammar-spelling",
      "A Vetted Pro with a perfect rating across 415 reviews who copy edits and proofreads books, ebooks and novels."),
    r("cj8168", "Callum", "Best for line editing without AI", "I will line edit and proofread your book without AI", "5.0", "315", "450",
      "/cj8168/proofread-edit-or-rewrite-any-document-essay-or-story",
      "A Vetted Pro with a perfect rating across 315 reviews who line edits and proofreads books by hand, without AI.",
      "Starts at 450 dollars."),
    r("arianelaurent", "Ariane L. Smith", "Best for nonfiction books", "I will expertly proofread and edit your nonfiction book", "5.0", "115", "550",
      "/arianelaurent/professionally-edit-your-book-in-3-days",
      "A Vetted Pro with a perfect rating who proofreads and edits nonfiction books.",
      "Starts at 550 dollars."),
    r("grammargal", "Stacey K.", "Most reviewed book editor and proofreader", "I will be your book editor and proofreader", "4.9", "1000", "150",
      "/grammargal/proofread-and-edit-up-to-2000-words-within-24hrs",
      "A Vetted Pro with more than a thousand reviews who edits and proofreads books."),
    r("robinoo", "Robin Schroffel", "Best for publishing-standard proofreading", "I will professionally proofread and edit your book to publishing standards", "4.9", "1000", "150",
      "/robinoo/professionally-proofread-1000-words",
      "A Vetted Pro with more than a thousand reviews who proofreads and edits books to publishing standards."),
    r("renaissancewrit", "Ashley Emma", "Best for book editing and proofreading", "I will expertly proofread or edit your book", "4.9", "374", "200",
      "/renaissancewrit/edit-or-proofread-your-book",
      "A Vetted Pro with 374 reviews who proofreads or edits books."),
], status="live")

add_picks.put("writing-translation/press-releases", [
    r("georgiaeaustin", "Georgia Austin", "Best budget pick for a newsworthy release", "I will write a newsworthy press release", "5.0", "348", "100",
      "/georgiaeaustin/write-a-buzzworthy-press-release",
      "A Vetted Pro with a perfect rating across 348 reviews who writes newsworthy press releases at a low starting price."),
    r("ambermeadows", "Amber Johnson", "Best for informative press releases", "I will write an informative press release", "5.0", "110", "100",
      "/ambermeadows/write-a-press-release",
      "A Vetted Pro with a perfect rating across 110 reviews who writes informative press releases."),
    r("halfdaymedia", "Half Day Media", "Best for writing plus distribution", "I will write and distribute a press release for your business", "5.0", "98", "150",
      "/halfdaymedia/write-a-compelling-press-release-for-your-business",
      "A Vetted Pro with a perfect rating who writes and distributes press releases for businesses."),
    r("kellywesteen", "Dr. Kelly W.", "Most reviewed for writing and distribution", "I will write and distribute your press release", "4.9", "634", "225",
      "/kellywesteen/create-a-knockout-press-release-that-gets-you-noticed",
      "A Vetted Pro with 634 reviews who writes and distributes press releases."),
    r("mymediabuzz", "Alegra H", "Best for media visibility", "I will boost your business visibility with a tailored press release", "4.9", "414", "100",
      "/mymediabuzz/create-your-press-release-for-maximum-media-exposure",
      "A Vetted Pro with 414 reviews who writes tailored press releases aimed at media exposure."),
    r("valanne", "Julia And Val", "Best for music and business releases", "I will write and distribute your press release or music press release", "4.9", "401", "190",
      "/valanne/write-a-compelling-press-release",
      "A Vetted Pro duo with 401 reviews who write and distribute press releases, including music releases."),
], status="live")

add_picks.put("writing-translation/ad-copy", [
    r("mongiardo", "Victoria M", "Best for high-converting ad copy", "I will write high-converting ad copy as your copywriter", "4.9", "82", "100",
      "/mongiardo/write-high-converting-ad-copy-as-your-copywriter",
      "A Vetted Pro with 82 reviews who writes high-converting ad copy."),
    r("mayasayvanova", "Maya S", "Best for ads across a full funnel", "I will do copywriting for sales funnel landing pages, ads, emails and video scripts", "4.9", "130", "165",
      "/mayasayvanova/write-start-to-end-sales-funnel",
      "A Vetted Pro with 130 reviews who writes ads together with landing pages, emails and video scripts."),
    r("georgiaeaustin", "Georgia Austin", "Best budget pick for ad content", "I will write ad content that converts", "4.8", "170", "100",
      "/georgiaeaustin/write-high-converting-content-for-your-ads",
      "A Vetted Pro with 170 reviews who writes ad content built to convert, at a low starting price."),
    r("francescatrdd", "Francesca T.", "Best for ads inside a marketing funnel", "I will do sales funnel and landing page copywriting that converts", "5.0", "169", "445",
      "/francescatrdd/do-marketing-funnels-copywriting-with-email-ads-sales-page",
      "A Vetted Pro with a perfect rating who writes marketing funnels covering email, ads and sales pages.",
      "Starts at 445 dollars."),
], status="live")

add_picks.put("online-marketing/e-commerce-seo", [
    r("numan_seo", "Numan Seo", "Most reviewed for on-page and technical SEO", "I will optimize on-page and technical SEO for WordPress, Shopify and more", "5.0", "1000", "250",
      "/numan_seo/do-onpage-seo-and-technical-optimization-of-wordpress-site",
      "A Vetted Pro with a perfect rating and more than a thousand reviews who optimizes on-page and technical SEO for WordPress, Shopify and other platforms."),
    r("mmashaw", "Meelad Mashaw", "Best for monthly SEO and content marketing", "I will do monthly SEO service for WordPress, Wix, Squarespace and Webflow", "5.0", "406", "600",
      "/mmashaw/be-your-seo-and-content-marketing-consultant",
      "A Vetted Pro with a perfect rating across 406 reviews who provides monthly SEO and content marketing.",
      "Starts at 600 dollars."),
    r("seemasingh5020", "Seema S", "Best for monthly Shopify SEO", "I will provide monthly Shopify SEO and AI optimization service", "5.0", "41", "295",
      "/seemasingh5020/provide-monthly-seo-service-to-your-shopify-website",
      "A Vetted Pro with a perfect rating who provides monthly SEO for Shopify stores.",
      "Fewer reviews than others on this list, at 41."),
    r("miranda_davis", "Miranda", "Best for Shopify SEO", "I will do ultimate Shopify SEO to boost traffic and sales", "4.9", "145", "170",
      "/miranda_davis/do-ultimate-shopify-seo-to-boost-traffic-and-ecommerce-website-sales-drastically",
      "A Vetted Pro with 145 reviews who does Shopify SEO aimed at traffic and sales."),
    r("manavsharma909", "Manav S", "Best for full monthly SEO", "I will do full monthly SEO service for Shopify, WordPress, Wix and Squarespace", "4.9", "124", "250",
      "/manavsharma909/do-semrush-seo-keyword-research-and-competitor-analysis",
      "A Vetted Pro with 124 reviews who provides full monthly SEO, including keyword research and competitor analysis."),
    r("usm403955", "Usm", "Best budget pick for on-page and technical SEO", "I will optimize e-commerce on-page and technical SEO for WordPress, Shopify and Wix", "4.8", "160", "100",
      "/usm403955/optimize-ecommerce-website-onpage-technical-seo-service-wordpress-shopify-wix",
      "A Vetted Pro with 160 reviews who optimizes on-page and technical SEO for e-commerce sites, at a low starting price."),
], status="live")

add_picks.put("video-animation/corporate-videos", [
    r("ionebutler", "Ione B", "Best for a live-action corporate explainer", "I will produce a live-action corporate explainer video with a female spokesperson", "5.0", "64", "395",
      "/ionebutler/produce-a-live-action-explainer-video-with-female-spokesperson-for-your-brand",
      "A Vetted Pro with a perfect rating who produces live-action corporate explainer videos with a spokesperson.",
      "Fewer reviews than others on this list, at 64."),
    r("kiramazur", "Mazu Agency", "Best agency for editing and post-production", "Our agency will do professional video editing and post-production", "4.9", "231", "350",
      "/kiramazur/do-professional-video-editing-and-post-production",
      "A Vetted Pro agency with 231 reviews that does video editing and post-production."),
    r("veroalana", "Veronica Alana", "Best for high-end corporate and tech videos", "I will edit a high-end corporate, tech or industrial video", "4.9", "156", "420",
      "/veroalana/edit-your-corporate-video-with-professional-quality",
      "A Vetted Pro with 156 reviews who edits corporate, tech and industrial videos.",
      "Starts at 420 dollars."),
    r("mridul4567", "Scaler Studios", "Best budget pick for editing corporate videos", "Our agency will edit your corporate videos professionally", "4.9", "123", "100",
      "/mridul4567/edit-your-corporate-videos-professionally",
      "A Vetted Pro agency with 123 reviews that edits corporate videos, at a low starting price."),
    r("paulnemeti", "Paul N", "Best for editing a company video", "I will professionally edit your company video", "4.9", "82", "405",
      "/paulnemeti/professionally-edit-your-company-video",
      "A Vetted Pro with 82 reviews who edits company videos.",
      "Starts at 405 dollars."),
    r("ciprisialis", "Poppy Advertise", "Best for corporate video ads", "Our agency will create high-impact corporate video ads and commercials", "4.8", "94", "150",
      "/ciprisialis/video-editing-services-for-your-ad-explainer-cinematic-inspirational-video",
      "A Vetted Pro agency with 94 reviews that creates corporate video ads and commercials."),
], status="live")
