import add_picks

add_picks.CHECKED = "2026-10-04"


def r(user, name, best_for, title, rating, reviews, price, url, why, watch_out=""):
    return dict(user=user, name=name, best_for=best_for, title=title, rating=rating, reviews=reviews,
                level="Vetted Pro", price=price, url=url, why=why, watch_out=watch_out)


add_picks.put("graphics-design/app-design", [
    r("huzaifa901", "Huzaifa Anas", "Best budget pick for app and web UI/UX", "I will do mobile app UI UX design or website UI UX design", "5.0", "147", "100",
      "/huzaifa901/create-ui-ux-design-for-mobile-app-and-prototypes",
      "A Vetted Pro with a perfect rating across 147 reviews who designs mobile app and website interfaces with prototypes, at a low starting price."),
    r("yulia_ui", "Yulia T.", "Best for polished iOS and Android design", "I will do UI UX design for a mobile app in Figma, for iOS or Android", "5.0", "105", "490",
      "/yulia_ui/design-mobile-app-ios-android",
      "A Vetted Pro with a perfect rating across 105 reviews who designs mobile apps for iOS and Android in Figma.",
      "Starts at 490 dollars."),
    r("syedmirajali", "Syed", "Best for complete app UI and UX", "I will design mobile app UI and UX in Figma", "5.0", "56", "150",
      "/syedmirajali/design-complete-ui-and-ux-design-for-ios-and-android-app",
      "A Vetted Pro with a perfect rating who designs complete UI and UX for iOS and Android apps in Figma.",
      "Fewer reviews than others on this list, at 56."),
    r("hipinspire", "Marko B.", "Most reviewed for creative app interfaces", "I will design mobile app UX UI in Figma", "4.9", "196", "200",
      "/hipinspire/design-a-creative-and-unique-mobile-app",
      "A Vetted Pro with 196 reviews who designs creative mobile app interfaces in Figma."),
    r("doctoruiux", "Muhammad Usman", "Best for Figma design systems and prototypes", "I will do Figma design, website UI UX design and mobile app UI design", "4.9", "133", "100",
      "/doctoruiux/do-figma-design-system-figma-prototype-ui-redesign-ui-mockups",
      "A Vetted Pro with 133 reviews who creates Figma design systems, prototypes and UI mockups, with a low starting price."),
    r("jubaerdr", "Jubaer Alam", "Best budget pick for mobile app UI", "I will create mobile app design UI UX with Figma", "4.9", "108", "100",
      "/jubaerdr/create-mobile-app-design-ui-ux-with-figma-xd-or-framer",
      "A Vetted Pro with 108 reviews who designs mobile app UI and UX in Figma, XD or Framer."),
], status="live")

add_picks.put("video-animation/logo-animation", [
    r("at_laude", "Edu", "Best overall for a tailored logo animation", "I will craft a logo animation", "5.0", "317", "360",
      "/at_laude/animate-your-logo-according-to-your-needs-192a",
      "A Vetted Pro with a perfect rating across 317 reviews who animates logos according to your needs."),
    r("animteam", "Lusine Bizon", "Best for a polished cool logo animation", "I will create cool logo animation", "5.0", "257", "500",
      "/animteam/create-some-cool-logo-animation",
      "A Vetted Pro with a perfect rating across 257 reviews who creates custom logo animations.",
      "Starts at 500 dollars."),
    r("aarongregory", "Aaron R.", "Best for a high-quality custom animation", "I will create a high-quality custom logo animation", "5.0", "130", "250",
      "/aarongregory/create-a-high-quality-custom-logo-animation",
      "A Vetted Pro with a perfect rating across 130 reviews who creates high-quality custom logo animations."),
    r("sickmotion", "Tomasz", "Best budget pick for a quick intro logo", "I will create a superb custom intro logo animation on time", "5.0", "126", "140",
      "/sickmotion/create-quality-custom-intro-logo-animation-on-time",
      "A Vetted Pro with a perfect rating across 126 reviews who creates custom intro logo animations on time, at a low starting price."),
    r("motiongrapherr", "Gayane G.", "Most reviewed for logo intros and outros", "I will create a custom logo animation intro video", "4.9", "787", "390",
      "/motiongrapherr/make-custom-intro-and-outro-animation-for-your-logo",
      "A Vetted Pro with 787 reviews who creates custom logo intro and outro animations."),
    r("artur8977", "Artur", "Best value for a simple professional animation", "I will create professional custom logo animation", "4.9", "574", "120",
      "/artur8977/make-a-simple-animation-of-your-logo",
      "A Vetted Pro with 574 reviews who creates simple professional logo animations at a low starting price."),
], status="live")

add_picks.put("video-animation/social-media-videos", [
    r("rexhinoganci92", "Rexhino Gançi", "Best for ongoing social content", "I will create content for your social media accounts", "5.0", "448", "100",
      "/rexhinoganci92/create-and-optimize-your-social-media-account",
      "A Vetted Pro with a perfect rating across 448 reviews who creates content for social media accounts."),
    r("radevradostin", "Radostin Radev", "Best for short ads and UGC-style videos", "I will create TikTok ads, YouTube Shorts, Reels and social ad UGC video", "5.0", "90", "200",
      "/radevradostin/create-tiktok-ads-youtube-shorts-reel-social-ad-ugc-video",
      "A Vetted Pro with a perfect rating who creates TikTok ads, YouTube Shorts, Reels and social ad videos."),
    r("lahcenessayeh", "Lahcen", "Most reviewed for engaging reels and TikToks", "I will edit your Instagram Reels, TikToks and Meta ads to be more engaging", "4.9", "862", "145",
      "/lahcenessayeh/add-engaging-subtitles-to-your-tiktok-and-instagram-videos",
      "A Vetted Pro with 862 reviews who edits short-form videos and ads to be more engaging."),
    r("designerreda123", "Reda Elmangad", "Best for motivational reels and shorts", "I will edit your Instagram Reels and TikToks to maximize engagement", "4.9", "331", "145",
      "/designerreda123/edit-viral-motivational-instagram-reels-and-youtube-shorts",
      "A Vetted Pro with 331 reviews who edits Instagram Reels, TikToks and YouTube Shorts."),
    r("mridul4567", "Scaler Studios", "Best budget pick for reels and video ads", "Our agency will edit Instagram Reels, YouTube Shorts, TikTok and video ads", "4.8", "176", "100",
      "/mridul4567/edit-instagram-reels-youtube-shorts-tiktok-and-video-ads",
      "A Vetted Pro agency with 176 reviews that edits reels, shorts, TikToks and video ads, at a low starting price."),
    r("viral_post", "Mat", "Best for viral-style short edits", "I will edit viral Instagram Reels, TikTok and YouTube Shorts", "4.8", "76", "200",
      "/viral_post/edit-your-instagram-video",
      "A Vetted Pro with 76 reviews who edits viral-style Instagram Reels, TikToks and YouTube Shorts."),
], status="live")

add_picks.put("writing-translation/website-content", [
    r("kellywesteen", "Dr. Kelly W.", "Best overall for conversion-focused web copy", "I will write website content that boosts profits", "5.0", "659", "175",
      "/kellywesteen/write-killer-copy-for-your-ads-emails-and-websites",
      "A Vetted Pro with a perfect rating across 659 reviews who writes website content aimed at boosting profits."),
    r("kevinschreck", "Kevin S.", "Best for SEO website content", "I will be your SEO website content writer and copywriter", "5.0", "122", "100",
      "/kevinschreck/write-optimized-website-content",
      "A Vetted Pro with a perfect rating who writes optimized website content, at a low starting price."),
    r("georgiaeaustin", "Georgia Austin", "Most reviewed for pages and landing pages", "I will write your website content and landing pages", "4.9", "1000", "125",
      "/georgiaeaustin/write-content-for-your-website",
      "A Vetted Pro with more than a thousand reviews who writes website content and landing pages."),
    r("zoewrites20", "Zoe D", "Best for SEO website copy", "I will write SEO website content as your copywriter", "4.9", "629", "150",
      "/zoewrites20/write-content-for-your-website",
      "A Vetted Pro with 629 reviews who writes SEO website content."),
    r("hamishlister", "Hamish Lister", "Best for engaging, SEO-aware copy", "I will write website copy and SEO website content", "4.9", "435", "175",
      "/hamishlister/write-something-engaging-compelling-and-exciting-for-you",
      "A Vetted Pro with 435 reviews who writes website copy and SEO content."),
    r("melissa_m_kinn", "Melissa M", "Best budget pick for web content", "I will write powerful website content", "4.9", "247", "100",
      "/melissa_m_kinn/write-content-for-you",
      "A Vetted Pro with 247 reviews who writes website content at a low starting price."),
], status="live")

add_picks.put("music-audio/audio-editing", [
    r("audiovideo_uk", "Lillo", "Most reviewed for podcast audio editing", "I will do podcast editing and edit audio in 3 days", "5.0", "515", "150",
      "/audiovideo_uk/edit-and-master-audio-for-podcast-to-commercial-standards",
      "A Vetted Pro with a perfect rating across 515 reviews who edits and masters podcast audio to commercial standards."),
    r("nmentana", "Norberto", "Best for repairing audio files", "I will repair and edit your audio file", "5.0", "165", "105",
      "/nmentana/repair-your-audio-file",
      "A Vetted Pro with a perfect rating across 165 reviews who repairs and edits audio files."),
    r("ericgoulard", "Eric Goulard", "Best for podcast and audiobook restoration", "I will do professional podcast editing, audiobook and audio restoration", "5.0", "161", "100",
      "/ericgoulard/record-your-audio-book-in-french",
      "A Vetted Pro with a perfect rating across 161 reviews who does podcast editing, audiobook work and audio restoration."),
    r("sunboatrecords", "Spyros Politis", "Best for advanced manual repairs", "I will provide advanced editing, repairs and restoration for audio or music", "5.0", "100", "150",
      "/sunboatrecords/provide-advanced-manual-audio-editing-and-repairs",
      "A Vetted Pro with a perfect rating across 100 reviews who does advanced manual editing, repair and restoration of audio."),
    r("mattheweveringh", "Matthew E", "Best budget pick for editing and mastering", "I will perform professional audio editing and master your audio", "5.0", "77", "100",
      "/mattheweveringh/professionally-produce-your-audio-to-the-highest-standard",
      "A Vetted Pro with a perfect rating who edits and masters audio, at a low starting price."),
    r("tro2789", "Trevor O", "Best for podcast audio and video", "I will edit, mix and master your podcast audio and video", "4.9", "389", "200",
      "/tro2789/edit-mix-and-master-your-podcast-audio",
      "A Vetted Pro with 389 reviews who edits, mixes and masters podcast audio and video."),
], status="live")

add_picks.put("video-animation/intro-and-outro-videos", [
    r("sergiymoroz", "Sergio M", "Best for YouTube intro and outro animation", "I will create a professional YouTube intro and outro animation", "5.0", "124", "250",
      "/sergiymoroz/creative-2d-logo-animation",
      "A Vetted Pro with a perfect rating across 124 reviews who creates YouTube intro and outro animations."),
    r("hipnosstudio", "Manuel T.", "Best for a stunning branded intro", "I will create a stunning intro or outro animation", "5.0", "62", "280",
      "/hipnosstudio/create-a-personalized-intro-for-your-brand",
      "A Vetted Pro with a perfect rating who creates personalized intro and outro animations for brands."),
    r("visimatic", "Obada", "Most reviewed for YouTube and podcast intros", "I will create a custom animated logo intro for YouTube, podcast and TikTok", "4.9", "394", "150",
      "/visimatic/create-a-professional-logo-animation-intro",
      "A Vetted Pro with 394 reviews who creates animated logo intros for YouTube, podcasts and social channels."),
    r("secret_pixel", "Abuzar K.", "Best budget pick for creators", "I will create unique custom intro, outro or logo animation for YouTube", "4.9", "68", "145",
      "/secret_pixel/create-unique-custom-logo-animation-for-your-youtube",
      "A Vetted Pro with 68 reviews who creates custom intro, outro and logo animations for YouTube."),
    r("screenhouse", "Jose Sh", "Best for high-impact intros", "I will create a high-impact intro or outro for you", "4.8", "158", "100",
      "/screenhouse/do-high-impact-intro-for-you",
      "A Vetted Pro with 158 reviews who creates high-impact intros and outros, at a low starting price."),
    r("monstoanimation", "Ashot S.", "Best for a quick custom logo intro", "I will create a unique custom logo animation intro", "4.8", "108", "100",
      "/monstoanimation/create-an-amazing-custom-logo-animation-for-your-brand",
      "A Vetted Pro with 108 reviews who creates custom logo animation intros, at a low starting price."),
], status="live")

add_picks.put("writing-translation/scriptwriting", [
    r("bkille", "Brian K", "Best budget pick for commercial scripts", "I will write an original TV commercial or video script", "5.0", "96", "100",
      "/bkille/write-a-tv-commercial-or-video-script",
      "A Vetted Pro with a perfect rating who writes original TV commercial and video scripts, at a low starting price."),
    r("mogb7d", "Olivia", "Best for a broadcast-style script", "I will write your professional script as a TV reporter", "5.0", "93", "125",
      "/mogb7d/freelance-article-and-scriptwriter",
      "A Vetted Pro with a perfect rating who writes professional scripts with a TV reporter background."),
    r("carrieglenn", "Carrie Glenn", "Best for video sales letter scripts", "I will write your VSL script with high-converting sales video copy", "5.0", "63", "685",
      "/carrieglenn/write-amazing-copy-for-your-sales-video-script",
      "A Vetted Pro with a perfect rating who writes video sales letter scripts.",
      "Premium pricing, starting around 685 dollars."),
    r("georgiaeaustin", "Georgia Austin", "Best for an engaging video script", "I will write your engaging video script", "4.9", "131", "100",
      "/georgiaeaustin/write-a-captivating-video-script",
      "A Vetted Pro with 131 reviews who writes engaging video scripts, at a low starting price."),
    r("mayasayvanova", "Maya S", "Best for video and YouTube ad scripts", "I will write an awesome video script or YouTube ads", "4.9", "85", "150",
      "/mayasayvanova/write-an-awesome-article",
      "A Vetted Pro with 85 reviews who writes video scripts and YouTube ad copy."),
    r("kbeamon", "Kalei", "Most reviewed for business video scripts", "I will write a professional video script for your business", "4.8", "960", "125",
      "/kbeamon/be-your-professional-script-writer-for-business-videos",
      "A Vetted Pro with 960 reviews who writes professional video scripts for businesses."),
], status="live")

add_picks.put("writing-translation/social-media-copywriting", [
    r("kristenjunne", "Kristen", "Most reviewed for social captions", "I will write your social media captions", "5.0", "217", "100",
      "/kristenjunne/write-your-social-media-captions",
      "A Vetted Pro with a perfect rating across 217 reviews who writes social media captions, at a low starting price."),
    r("ambermeadows", "Amber Johnson", "Best for SEO-aware captions", "I will write SEO-driven social media captions", "5.0", "75", "100",
      "/ambermeadows/write-your-social-media-captions",
      "A Vetted Pro with a perfect rating who writes SEO-driven social media captions."),
    r("georgiaeaustin", "Georgia Austin", "Best for engagement-focused posts", "I will write social media content that drives engagement", "4.9", "319", "100",
      "/georgiaeaustin/write-engaging-social-media-captions",
      "A Vetted Pro with 319 reviews who writes social media content aimed at engagement."),
    r("mongiardo", "Victoria M", "Best for captions and posts from a copywriter", "I will write social media captions and posts as your copywriter", "4.8", "60", "100",
      "/mongiardo/write-engaging-social-media-captions-and-posts",
      "A Vetted Pro with 60 reviews who writes social media captions and posts.",
      "Fewer reviews than others on this list, at 60."),
], status="live")
