import add_picks

add_picks.CHECKED = "2026-10-04"


def r(user, name, best_for, title, rating, reviews, price, url, why, watch_out=""):
    return dict(user=user, name=name, best_for=best_for, title=title, rating=rating, reviews=reviews,
                level="Vetted Pro", price=price, url=url, why=why, watch_out=watch_out)


add_picks.put("music-audio/songwriting", [
    r("matt_sky", "Matt Sky", "Best overall for a songwriter who also performs", "I will be your male singer songwriter and producer for your song", "5.0", "753", "110",
      "/matt_sky/be-your-male-singer-songwriter-and-producer-for-your-song",
      "A Vetted Pro with a perfect rating across 753 reviews who writes, sings and produces songs."),
    r("tobywilson664", "Tobias Wilson", "Best for turning lyrics into a finished track", "I will turn your lyrics into a radio-ready, fully produced track", "5.0", "590", "150",
      "/tobywilson664/turn-your-lyrics-into-a-radio-ready-fully-produced-track",
      "A Vetted Pro with a perfect rating across 590 reviews who turns existing lyrics into fully produced tracks."),
    r("gregvkmusic", "Greg VK", "Best for lyrics and melody from scratch", "I will write lyrics and melody for your song", "5.0", "464", "100",
      "/gregvkmusic/write-lyrics-and-melody-for-your-song",
      "A Vetted Pro with a perfect rating across 464 reviews who writes both lyrics and melody."),
    r("damooch916", "Tommy J", "Best for a piano-based love song", "I will write and record a love song on the piano", "5.0", "383", "100",
      "/damooch916/write-and-record-a-love-song-on-the-piano",
      "A Vetted Pro with a perfect rating across 383 reviews who writes and records piano love songs."),
    r("jayvocals", "Jamie Wiltshire", "Best for ghostwriting and lyrics", "I will be your songwriter, ghostwriter or lyricist", "5.0", "183", "150",
      "/jayvocals/be-your-songwriter-ghostwriter-or-lyricist",
      "A Vetted Pro with a perfect rating who works as a songwriter, ghostwriter or lyricist."),
    r("joeybuss", "Joey B", "Best for catchy pop-style hooks", "I will write you a catchy song with lyrics and melodies", "5.0", "138", "150",
      "/joeybuss/let-me-write-you-a-catchy-song-with-lyrics-and-melodies",
      "A Vetted Pro with a perfect rating who writes catchy songs with lyrics and melodies."),
], status="live")

add_picks.put("music-audio/beat-making", [
    r("vitaliezekiev", "Vitali E", "Best overall for custom production", "I will produce music and a hit-style song for you", "5.0", "213", "100",
      "/vitaliezekiev/produce-music-and-number-1-hit-song-for-you",
      "A Vetted Pro with a perfect rating across 213 reviews who produces custom music."),
    r("hssmusica", "Hernan S", "Best for EDM, pop and hip hop production", "I will be your music producer for custom beats, pop and hip hop", "5.0", "187", "150",
      "/hssmusica/your-edm-ghost-producer",
      "A Vetted Pro with a perfect rating across 187 reviews who produces custom beats across EDM, pop and hip hop."),
    r("masterfademusic", "Masterfademusic", "Best for custom hip hop or rap beats", "I will produce a custom hip hop or rap beat for your project", "5.0", "77", "125",
      "/masterfademusic/produce-an-custom-hip-hop-or-rap-beat-for-your-project-bda7",
      "A Vetted Pro with a perfect rating who produces custom hip hop and rap beats."),
    r("fernandodarder", "Fernando j.D", "Best for original beats with lots of reviews", "I will create an original beat for you", "4.9", "358", "100",
      "/fernandodarder/create-an-original-beat-for-you",
      "A Vetted Pro with 358 reviews who creates original beats."),
], status="live")

add_picks.put("music-audio/custom-songs", [
    r("gossamer5", "Gossamer5", "Best for EDM songs with vocals and lyrics", "I will sing and write lyrics on your EDM song", "5.0", "198", "300",
      "/gossamer5/sing-and-write-lyrics-on-your-edm-song",
      "A Vetted Pro with a perfect rating across 198 reviews who writes lyrics and sings on EDM tracks.",
      "Starts at 300 dollars."),
    r("ntmartin", "Martin T.", "Best for a fully produced pop song", "I will produce your pop song", "5.0", "131", "250",
      "/ntmartin/produce-your-pop-song",
      "A Vetted Pro with a perfect rating across 131 reviews who produces pop songs."),
    r("christinartnd", "Christina R", "Best budget pick for a female vocalist and songwriter", "I will be your unique female songwriter and singer", "5.0", "128", "100",
      "/christinartnd/be-your-unique-female-songwriter-singer",
      "A Vetted Pro with a perfect rating across 128 reviews who writes and sings custom songs, at a low starting price."),
    r("chudak14", "Carter", "Best for a quick turnaround", "I will write a hit song in less than 24 hours", "5.0", "99", "250",
      "/chudak14/write-a-hit-song-in-less-than-24-hours",
      "A Vetted Pro with a perfect rating who offers songs written in a short time."),
    r("jemma_sings", "Jemma Webb", "Best for a full song with vocal production", "I will sing an entire song with full vocal production", "4.9", "145", "230",
      "/jemma_sings/sing-an-entire-song-with-full-vocal-production",
      "A Vetted Pro with 145 reviews who sings and produces full songs."),
    r("adamblotner", "Adam B", "Best for a custom song plus an animated video", "I will write a custom song and animate a video", "4.9", "108", "295",
      "/adamblotner/write-a-custom-song-and-animate-a-video",
      "A Vetted Pro with 108 reviews who writes a custom song and animates a video for it."),
], status="live")

add_picks.put("music-audio/session-musicians", [
    r("orishlez", "Ori Shlez", "Best for keyboard and piano tracks", "I will record a keyboard or piano track for any song", "5.0", "588", "100",
      "/orishlez/record-keyboard-piano-track-for-any-song",
      "A Vetted Pro with a perfect rating across 588 reviews who records keyboard and piano parts."),
    r("adamwardguitar", "Adam Ward", "Best for acoustic guitar", "I will record beautiful acoustic guitar tracks on your song", "5.0", "200", "135",
      "/adamwardguitar/record-beautiful-acoustic-guitar-tracks-on-your-song",
      "A Vetted Pro with a perfect rating across 200 reviews who records acoustic guitar parts."),
    r("maciejplacej", "Maciej S", "Best for upright and double bass", "I will record double bass or upright bass for you", "5.0", "202", "120",
      "/maciejplacej/record-double-bass-upright-bass-for-you",
      "A Vetted Pro with a perfect rating across 202 reviews who records double bass and upright bass."),
    r("bass50", "Dmitry Lisenko", "Best for bass parts", "I will record an awesome bass part for your song", "5.0", "174", "100",
      "/bass50/record-awesome-bass-part-for-your-song",
      "A Vetted Pro with a perfect rating across 174 reviews who records bass parts."),
    r("fede_redrummer", "Fede Gucciardo", "Best for R&B and hip hop drums", "I will record pro R&B and hip hop drums for your tracks", "5.0", "74", "100",
      "/fede_redrummer/record-affordable-but-pro-rnb-hip-hop-drums-for-your-tracks",
      "A Vetted Pro with a perfect rating who records R&B and hip hop drums."),
    r("luquibass", "Luca G.", "Best for electric bass guitar", "I will record pro-quality bass guitar for your project", "4.9", "202", "100",
      "/luquibass/record-pro-quality-bass-guitar-for-your-project",
      "A Vetted Pro with 202 reviews who records bass guitar for music projects."),
], status="live")

add_picks.put("music-audio/composers", [
    r("roxane_s", "Roxane S", "Best overall for a premium soundtrack", "I will compose, produce and record a premium-quality soundtrack", "5.0", "124", "100",
      "/roxane_s/compose-produce-record-premium-quality-music-soundtrack",
      "A Vetted Pro with a perfect rating across 124 reviews who composes, produces and records soundtracks."),
    r("stavrosstavrou", "Stavros Stavrou", "Best for epic game or film music", "I will create an epic soundtrack for video games or movies", "5.0", "104", "100",
      "/stavrosstavrou/create-an-epic-soundtrack-for-video-games-or-movies",
      "A Vetted Pro with a perfect rating across 104 reviews who composes epic music for games and films."),
    r("nelaruiz", "Nela Ruiz", "Best for short animations and videos", "I will create the sound for your short animation or video", "5.0", "102", "150",
      "/nelaruiz/create-the-sound-for-your-short-animation-or-video",
      "A Vetted Pro with a perfect rating across 102 reviews who creates music and sound for short animations and videos."),
    r("mnproduction_", "MN Production", "Best for orchestral arrangements", "I will write the orchestral arrangement of your music", "4.8", "74", "130",
      "/mnproduction_/write-the-orchestral-arrangement-of-your-music",
      "A Vetted Pro with 74 reviews who writes orchestral arrangements."),
    r("rorylaws", "Rory Laws", "Best for scoring films and games", "I will score your short film, videogame or any project", "4.9", "43", "350",
      "/rorylaws/score-your-short-film-videogame-or-any-project",
      "A Vetted Pro who scores short films, video games and other projects.",
      "Starts at 350 dollars, with fewer reviews than others here."),
], status="live")

add_picks.put("programming-tech/webflow", [
    r("edharutyunyan", "Ed H.", "Best budget pick for Figma-to-Webflow", "I will design and develop a custom Webflow website or convert Figma", "5.0", "234", "110",
      "/edharutyunyan/convert-any-design-to-responsive-webflow-website",
      "A Vetted Pro with a perfect rating across 234 reviews who builds Webflow sites and converts designs to responsive pages, at a low starting price."),
    r("dereksiu", "Derek Siu", "Best for building, fixing or updating a Webflow site", "I will design, develop, convert, update or fix your Webflow website", "5.0", "151", "380",
      "/dereksiu/turn-your-sexy-ass-web-design-into-a-fully-responsive-webflow-site",
      "A Vetted Pro with a perfect rating across 151 reviews who builds, converts, updates and fixes Webflow sites."),
    r("szilard_", "Szilard", "Best for a custom brand website", "I will design a custom Webflow website for serious brands", "5.0", "119", "1295",
      "/szilard_/create-an-awesome-webflow-website",
      "A Vetted Pro with a perfect rating across 119 reviews who designs custom Webflow sites for brands.",
      "Premium pricing, starting near 1,295 dollars."),
    r("ydrawing", "Catalin D.", "Best for design plus development", "I will create a Webflow design and develop your Webflow website", "5.0", "115", "695",
      "/ydrawing/design-and-build-a-custom-webflow-website",
      "A Vetted Pro with a perfect rating across 115 reviews who handles both the design and the Webflow build."),
    r("kianaaz", "Kiki", "Best for responsive builds and redesigns", "I will be your Webflow developer for website design and redesign", "5.0", "109", "350",
      "/kianaaz/develop-a-fully-responsive-website-with-webflow",
      "A Vetted Pro with a perfect rating across 109 reviews who builds responsive Webflow sites and redesigns."),
    r("keetalux", "Mo K.", "Best for a premium business site", "I will design and build a premium Webflow website for your business", "5.0", "92", "495",
      "/keetalux/design-and-develop-a-webflow-website",
      "A Vetted Pro with a perfect rating who designs and builds Webflow sites for businesses."),
], status="live")

add_picks.put("programming-tech/android-app-development", [
    r("dharmaniapps07", "Vivek Dharmani", "Best overall for Android and iOS apps", "I will do mobile app development for iOS, Android and Flutter", "5.0", "640", "180",
      "/dharmaniapps07/develop-high-quality-of-android-and-ios-app",
      "A Vetted Pro with a perfect rating across 640 reviews who builds Android and iOS apps."),
    r("farooq_arshad", "Jeux Developers", "Best for a fast Android build", "We will develop an Android application in 24 hours", "5.0", "502", "100",
      "/farooq_arshad/develop-a-android-application-in-24h",
      "A Vetted Pro agency with a perfect rating across 502 reviews that builds Android applications."),
    r("pn_logistics", "Pankush", "Best for native Kotlin and Swift apps", "I will do Android and iOS mobile app development with Swift and Kotlin", "5.0", "294", "400",
      "/pn_logistics/be-your-android-ios-developer-for-developing-mobile-app",
      "A Vetted Pro with a perfect rating across 294 reviews who builds native apps in Kotlin and Swift."),
    r("codobux_agency", "Codobux", "Best budget pick for Android and iOS apps", "We will build mobile apps for iOS and Android", "5.0", "145", "120",
      "/codobux_agency/building-mobile-app-development-ios-android-app-developer",
      "A Vetted Pro agency with a perfect rating across 145 reviews that builds Android and iOS apps, at a low starting price."),
    r("twityfruity", "Techfoxers", "Best for Android-only projects", "We will develop an Android app or be your Android app developer", "5.0", "66", "200",
      "/twityfruity/do-any-android-app-development-professionally",
      "A Vetted Pro agency with a perfect rating that focuses on Android app development."),
    r("mohsiinshah797", "Mohsin S", "Best for Kotlin or Java apps and bug fixes", "I will do Android app development in Kotlin and Java", "5.0", "54", "500",
      "/mohsiinshah797/develop-android-applications-and-fix-bugs-in-android-studio",
      "A Vetted Pro with a perfect rating who develops Android apps in Kotlin and Java and fixes bugs in Android Studio."),
], status="live")

add_picks.put("programming-tech/ios-app-development", [
    r("micmed", "Harminder S", "Best overall for iOS and Android apps", "I will do mobile app development for iOS and Android", "5.0", "385", "100",
      "/micmed/be-your-mobile-app-developer-to-develop-android-ios-mobile-app",
      "A Vetted Pro with a perfect rating across 385 reviews who builds iOS and Android apps."),
    r("dharmesh304", "Dharmesh K", "Best for iPhone and iPad apps in Swift", "I will develop a custom iOS app for iPhone and iPad using Swift", "5.0", "354", "300",
      "/dharmesh304/do-iphone-ipad-professional-apps-for-you",
      "A Vetted Pro with a perfect rating across 354 reviews who builds custom iPhone and iPad apps in Swift."),
    r("pn_logistics", "Pankush", "Best for native Swift and Kotlin apps", "I will do Android and iOS mobile app development with Swift and Kotlin", "5.0", "294", "400",
      "/pn_logistics/be-your-android-ios-developer-for-developing-mobile-app",
      "A Vetted Pro with a perfect rating across 294 reviews who builds native apps in Swift and Kotlin."),
    r("sibtainali491", "Sibtain Ali", "Best for SwiftUI features and app launch", "I will complete and launch your iOS app in Swift and SwiftUI", "5.0", "211", "200",
      "/sibtainali491/add-features-in-you-swiftui-app",
      "A Vetted Pro with a perfect rating across 211 reviews who completes and launches iOS apps in Swift and SwiftUI."),
    r("dharmaniapps07", "Vivek Dharmani", "Best for native Swift iPhone apps", "I will build a native Swift iOS iPhone app", "5.0", "181", "200",
      "/dharmaniapps07/do-native-ios-app-development",
      "A Vetted Pro with a perfect rating across 181 reviews who builds native iPhone apps in Swift."),
    r("pankaj711", "iTechnoLabs", "Best budget pick for a store or marketplace app", "We will do iOS app development in Swift", "5.0", "81", "100",
      "/pankaj711/create-ecommerce-and-classified-mobile-application",
      "A Vetted Pro agency with a perfect rating who builds iOS apps in Swift, including e-commerce and classified apps, at a low starting price."),
], status="live")
