import add_picks

add_picks.CHECKED = "2026-10-04"


def r(user, name, best_for, title, rating, reviews, price, url, why, watch_out=""):
    return dict(user=user, name=name, best_for=best_for, title=title, rating=rating, reviews=reviews,
                level="Vetted Pro", price=price, url=url, why=why, watch_out=watch_out)


add_picks.put("graphics-design/brand-style-guides", [
    r("mrtranscendence", "Abhi C", "Best budget pick with a large track record", "I will design a business logo, brand style guide and brand identity", "4.9", "497", "125",
      "/mrtranscendence/design-a-professional-logo-brand-book-and-corporate-brand-identity",
      "A Vetted Pro with nearly 500 reviews who combines a logo with a brand book and corporate identity at a low starting price."),
    r("kellyrother", "Kelly R", "Best for a strategic brand identity", "I will design your strategic brand identity, logo and style guide", "4.9", "248", "270",
      "/kellyrother/create-your-brand-style-guide",
      "A Vetted Pro with 248 reviews who builds a strategic brand identity, logo and style guide together."),
    r("weperfectionist", "San", "Best for a logo plus brand book", "I will design a business logo, brand style guide and corporate brand identity guidelines", "4.9", "226", "135",
      "/weperfectionist/design-a-business-logo-brand-book-and-corporate-brand-identity-guidelines",
      "A Vetted Pro with 226 reviews who delivers a logo, brand book and corporate identity guidelines."),
    r("santosstudio", "Sara Santos", "Best for a high-level, in-depth guide", "I will develop a high level brand style guide for your business", "4.9", "217", "1200",
      "/santosstudio/create-an-outstanding-brand",
      "A Vetted Pro with 217 reviews who develops a detailed brand style guide for a business.",
      "Premium pricing, starting around 1,200 dollars."),
    r("fazdesign", "Felix Zambrano", "Best for B2B brands", "I will design a B2B brand identity and style guide", "4.9", "210", "350",
      "/fazdesign/design-a-professional-brand-identity-and-guideline",
      "A Vetted Pro with 210 reviews who designs brand identities and style guides aimed at B2B companies."),
    r("brandidentityco", "Tariq Mahmood", "Best for a minimalist corporate identity", "I will do a complete logo and brand identity design or brand style guide", "4.8", "378", "195",
      "/brandidentityco/design-corporate-minimalist-logo-brand-identity-style-guides",
      "A Vetted Pro with 378 reviews who designs corporate, minimalist logos together with brand identity and style guides."),
], status="live")

add_picks.put("graphics-design/ux-design", [
    r("kianaaz", "Kiki", "Most reviewed for web and app UX", "I will do Figma website and landing page UI UX design", "5.0", "581", "270",
      "/kianaaz/design-unique-web-and-app-ui-ux-with-prototype",
      "A Vetted Pro with a perfect rating across 581 reviews who designs web and app interfaces in Figma with a prototype."),
    r("designhouseinc", "Jay T.", "Best for custom website UX/UI", "I will do unique website UI UX design or a landing page in Figma", "5.0", "548", "350",
      "/designhouseinc/design-custom-and-unique-ui-ux-for-your-web-and-application-presence",
      "A Vetted Pro with a perfect rating across 548 reviews who designs custom website and application interfaces in Figma."),
    r("tanasiychuk8", "Mykola T", "Best for responsive website design", "I will design a modern Figma website UI UX or a landing page that converts", "5.0", "447", "495",
      "/tanasiychuk8/create-a-responsive-design-for-your-website-in-16-hours",
      "A Vetted Pro with a perfect rating across 447 reviews who designs responsive website interfaces in Figma.",
      "Starts at 495 dollars."),
    r("robinpatoliya", "Poki Studios", "Best agency for modern web UX", "Our agency will design a modern Figma website UI UX for your business", "5.0", "377", "600",
      "/robinpatoliya/create-stunning-user-interfaces-and-experiences-for-your-business",
      "A Vetted Pro agency with a perfect rating across 377 reviews that designs modern website interfaces in Figma.",
      "Agency pricing, starting at 600 dollars."),
    r("rockitbat", "Shajee A", "Best for a mobile app UI/UX", "I will create a unique mobile app UI UX design", "5.0", "158", "600",
      "/rockitbat/design-mobile-app-ui-ux",
      "A Vetted Pro with a perfect rating across 158 reviews who designs unique mobile app interfaces.",
      "Starts at 600 dollars."),
    r("pooja_kmt", "Pooja", "Best budget pick for app UX", "I will do mobile app UI UX design", "4.9", "188", "120",
      "/pooja_kmt/do-mobile-app-design-in-figma",
      "A Vetted Pro with 188 reviews who designs mobile app interfaces in Figma, with a low starting price."),
], status="live")

add_picks.put("online-marketing/search-engine-marketing-sem", [
    r("mace_lets_grow", "Mace", "Best overall for ongoing Google Ads management", "I will set up and manage your Google Ads PPC campaigns", "5.0", "564", "295",
      "/mace_lets_grow/create-advanced-google-ads-campaigns-ongoing-management",
      "A Vetted Pro with a perfect rating across 564 reviews who creates advanced Google Ads campaigns with ongoing management."),
    r("chris_299", "Chris", "Best value for setup and management", "I will set up and manage your Google Ads PPC campaigns", "5.0", "258", "140",
      "/chris_299/setup-and-manage-your-google-ads-adwords-ppc-campaigns",
      "A Vetted Pro with a perfect rating across 258 reviews who sets up and manages Google Ads campaigns, at a low starting price."),
    r("velvaragency", "VELVAR Agency", "Best for campaign setup with a review call", "I will set up your Google Ads PPC campaigns and meet you to review", "5.0", "240", "120",
      "/velvaragency/setup-your-google-ads-ppc-campaigns-and-meet-you-to-review",
      "A Vetted Pro agency with a perfect rating across 240 reviews that sets up Google Ads campaigns and meets you to review them."),
    r("texomarketing", "Kamil", "Best for a Google Ads consultation", "I will set up and manage ultra profitable Google Ads PPC campaigns", "5.0", "209", "130",
      "/texomarketing/do-a-google-ads-consultation-with-you",
      "A Vetted Pro with a perfect rating across 209 reviews who sets up and manages Google Ads campaigns and offers consultations."),
    r("manavchawla", "Manav C", "Most reviewed, budget friendly", "I will set up Google Ads AdWords PPC campaigns", "4.9", "1000", "125",
      "/manavchawla/set-up-and-manage-your-google-ads-also-generate-revenue",
      "A Vetted Pro with more than a thousand reviews who sets up and manages Google Ads campaigns."),
    r("yrknti", "Yarkin Tiras", "Best for setup plus management", "I will set up and manage Google Ads PPC campaigns", "4.9", "405", "350",
      "/yrknti/quickly-setup-and-manage-google-ads-campaigns",
      "A Vetted Pro with 405 reviews who sets up and manages Google Ads campaigns.",
      "Starts at 350 dollars."),
], status="live")

add_picks.put("writing-translation/email-copy", [
    r("neidertmike", "Michael Neidert", "Best for a 10-email sales funnel", "I will write sales emails for your business, boosting sales conversion", "5.0", "168", "120",
      "/neidertmike/write-an-effective-10-email-sales-funnel-for-you",
      "A Vetted Pro with a perfect rating across 168 reviews who writes a ten-email sales funnel to lift conversion."),
    r("kevinschreck", "Kevin S.", "Best for newsletters and sales emails", "I will do newsletter and sales email copywriting", "5.0", "145", "100",
      "/kevinschreck/write-sales-email-marketing-campaigns-and-newsletters",
      "A Vetted Pro with a perfect rating across 145 reviews who writes newsletters, sales emails and email marketing campaigns."),
    r("jorgleach", "Paul", "Best for an email sequence", "I will create a killer email sequence", "5.0", "86", "125",
      "/jorgleach/create-a-killer-email-sequence",
      "A Vetted Pro with a perfect rating who writes complete email sequences."),
    r("rafaelmenesesjr", "Rafael Meneses", "Most reviewed email copywriter", "I will provide email copywriting that converts", "4.9", "417", "100",
      "/rafaelmenesesjr/write-powerful-email-copy-that-converts",
      "A Vetted Pro with 417 reviews who writes email copy built for conversion."),
    r("georgiaeaustin", "Georgia Austin", "Best for persuasive marketing campaigns", "I will write persuasive email content that sells", "4.9", "366", "100",
      "/georgiaeaustin/write-persuasive-email-marketing-campaigns",
      "A Vetted Pro with 366 reviews who writes persuasive email marketing campaigns."),
    r("donniedarkolove", "Chanel C.", "Best for sales email sequences", "I will write a persuasive marketing email campaign or sales copy sequence", "4.9", "181", "100",
      "/donniedarkolove/write-a-persuasive-marketing-email-that-gets-results",
      "A Vetted Pro with 181 reviews who writes persuasive marketing email campaigns and sales sequences."),
], status="live")

add_picks.put("graphics-design/flyer-design", [
    r("shawnchenpro", "Shawn", "Best for professional flyers and one-pagers", "I will design a professional flyer or one pager for you", "5.0", "214", "250",
      "/shawnchenpro/design-professionals-flyer-or-one-pager-for-you",
      "A Vetted Pro with a perfect rating across 214 reviews who designs professional flyers and one-page sheets.",
      "Starts at 250 dollars, above most sellers here."),
    r("leolez", "Leonardo", "Best for a professional business flyer", "I will design a professional business flyer", "5.0", "64", "220",
      "/leolez/design-a-professional-quality-flyer",
      "A Vetted Pro with a perfect rating who designs professional business flyers.",
      "Fewer reviews than others on this list, at 64."),
    r("madridny", "Oscar Polanco", "Most reviewed for print flyers and postcards", "I will design a professional flyer, postcard, pamphlet or door hanger", "4.9", "593", "160",
      "/madridny/design-a-professional-flyer",
      "A Vetted Pro with 593 reviews who designs flyers, postcards, pamphlets and door hangers."),
    r("designerheather", "Heather", "Best for a business flyer", "I will design your business flyer", "4.9", "562", "180",
      "/designerheather/design-your-business-flyer",
      "A Vetted Pro with 562 reviews who designs business flyers."),
    r("lenasemenkova", "Lena S.", "Best budget pick for a unique flyer", "I will design you a unique flyer", "4.9", "136", "115",
      "/lenasemenkova/design-you-a-unique-flyer",
      "A Vetted Pro with 136 reviews who designs unique flyers, at the lowest starting price in this list."),
    r("tonymidi", "Wolfordeer", "Best for an illustrated flyer", "I will create a cool flyer design with cool illustration", "4.8", "125", "145",
      "/tonymidi/create-cool-flyer-design-with-cool-illustration",
      "A Vetted Pro with 125 reviews who designs flyers with illustration."),
], status="live")

add_picks.put("graphics-design/infographic-design", [
    r("petercover", "Lan V", "Best for a professional custom infographic", "I will create a top quality professional infographic design", "4.9", "196", "150",
      "/petercover/design-a-professional-infographic",
      "A Vetted Pro with 196 reviews who creates professional infographic designs."),
    r("deryano", "Omar Studios", "Best for product and Amazon infographics", "I will design converting Amazon listing images and product infographics", "4.9", "835", "100",
      "/deryano/design-amazon-images-infographics-and-lifestyle",
      "A Vetted Pro with 835 reviews who designs product infographics and listing images for Amazon sellers.",
      "Focused on marketplace listings, so check the fit for report or editorial infographics."),
    r("madridny", "Oscar Polanco", "Best for data-driven infographics", "I will design data-driven infographics for LinkedIn, reports and investors", "4.8", "417", "160",
      "/madridny/create-professional-design-infographic",
      "A Vetted Pro with 417 reviews who designs data-driven infographics for LinkedIn, reports and investors."),
    r("aistegi", "Aiste", "Best budget pick for an infographic", "I will design a professional infographic", "4.8", "318", "100",
      "/aistegi/design-a-professional-infographic",
      "A Vetted Pro with 318 reviews who designs professional infographics, at a low starting price."),
    r("dreejc7", "Dee7 Studio", "Best agency for custom infographics", "Our agency will design a unique customized infographic", "4.8", "243", "195",
      "/dreejc7/create-a-unique-infographic-custom-infographic-design",
      "A Vetted Pro agency with 243 reviews that designs custom infographics."),
    r("a_samadshah", "desverto", "Best for Amazon listing infographics", "Our agency will design Amazon listing images and infographics", "4.8", "213", "100",
      "/a_samadshah/design-amazon-product-listing-images-that-sell-like-crazy-0e84",
      "A Vetted Pro agency with 213 reviews that designs Amazon listing images and infographics.",
      "Focused on marketplace listings."),
], status="live")

add_picks.put("graphics-design/t-shirts-and-merchandise", [
    r("sevenheavens_", "Gel", "Best for vintage hand-drawn designs", "I will do graphic t-shirt design with a hand-drawn vintage style", "4.9", "669", "100",
      "/sevenheavens_/make-t-shirt-design-with-hand-drawn-vintage-illustration",
      "A Vetted Pro with 669 reviews who creates hand-drawn vintage-style t-shirt designs, at a low starting price."),
    r("gabykatten", "Gaby K", "Best budget pick for illustrated shirts", "I will create illustrations for t-shirt designs or any purpose", "4.9", "273", "100",
      "/gabykatten/create-illustrations-for-t-shirt-designs",
      "A Vetted Pro with 273 reviews who creates illustrations for t-shirt designs and other uses."),
    r("kenduren", "Gubug Kenduren", "Best for shirt and sticker designs", "I will create a custom design sticker and t-shirt", "4.9", "270", "125",
      "/kenduren/create-a-custom-design-sticker-and-tshirt",
      "A Vetted Pro with 270 reviews who creates custom designs for stickers and t-shirts."),
    r("oleksii94", "Oleksii", "Best for cartoon-style shirt illustration", "I will create a custom cartoon t-shirt illustration for your brand", "4.9", "158", "200",
      "/oleksii94/create-illustrations-for-print-t-shirt-design",
      "A Vetted Pro with 158 reviews who creates custom cartoon t-shirt illustrations for brands."),
    r("wowyellow", "Jen P", "Best for custom illustrated graphic tees", "I will create a custom illustrated graphic t-shirt design", "4.9", "93", "225",
      "/wowyellow/create-a-custom-illustrated-t-shirt-design",
      "A Vetted Pro with 93 reviews who creates custom illustrated graphic t-shirt designs."),
    r("sergeysamsonov", "Sergey S", "Most reviewed for streetwear and hoodies", "I will design streetwear clothing, merch, graphic t-shirts and hoodies", "4.8", "1000", "170",
      "/sergeysamsonov/design-modern-streetwear-prints",
      "A Vetted Pro with more than a thousand reviews who designs streetwear merch, graphic t-shirts and hoodies."),
], status="live")

add_picks.put("graphics-design/image-editing", [
    r("valmirmorina175", "Valmir Morina", "Most reviewed for general Photoshop work", "I will do professional Photoshop editing and product image editing", "5.0", "1000", "100",
      "/valmirmorina175/do-any-photoshop-work",
      "A Vetted Pro with a perfect rating and more than a thousand reviews who does Photoshop editing and product image editing."),
    r("artemretouching", "Sasa M.", "Best for high-end retouching and color grading", "I will do high-end photo retouching and professional color grading", "5.0", "610", "100",
      "/artemretouching/professionally-retouch-and-color-grade-your-photos",
      "A Vetted Pro with a perfect rating across 610 reviews who retouches photos and does professional color grading."),
    r("guilhermezanchi", "Gui Zanchi", "Best for beauty and portrait retouching", "I will do professional beauty and portrait photo retouching", "5.0", "346", "100",
      "/guilhermezanchi/professionally-retouch-and-edit-your-photo-in-photoshop",
      "A Vetted Pro with a perfect rating across 346 reviews who retouches beauty and portrait photos."),
    r("elizaisseliza", "Eliza P.", "Best for portrait and skin retouching", "I will professionally retouch and edit your photo in Photoshop", "4.9", "351", "120",
      "/elizaisseliza/do-professional-portrait-beauty-and-skin-photoshop-retouch",
      "A Vetted Pro with 351 reviews who retouches portraits and skin in Photoshop."),
    r("valeriasturza", "Valeria S.", "Best for headshot retouching", "I will do photo editing, Photoshop and headshot retouching", "4.9", "245", "100",
      "/valeriasturza/do-photoshop-editing-high-end-photo",
      "A Vetted Pro with 245 reviews who does high-end photo editing and headshot retouching."),
    r("retouchfast", "Argiris Maipas", "Best for product photo retouching", "I will do professional product photo editing and retouching", "4.9", "197", "100",
      "/retouchfast/edit-and-do-high-end-retouch-product-photos",
      "A Vetted Pro with 197 reviews who edits and retouches product photos."),
], status="live")
