import add_picks

add_picks.CHECKED = "2026-10-05"


def r(user, name, best_for, title, rating, reviews, price, url, why, watch_out=""):
    return dict(user=user, name=name, best_for=best_for, title=title, rating=rating, reviews=reviews,
                level="Vetted Pro", price=price, url=url, why=why, watch_out=watch_out)


add_picks.put("business/business-plans", [
    r("saim_9", "Saim", "Best overall for plans with financial projections", "I will prepare financial projections, a business plan and forecasts", "5.0", "677", "100",
      "/saim_9/prepare-financial-projections-business-plan-and-forecasts",
      "A Vetted Pro with a perfect rating across 677 reviews who prepares business plans together with financial projections and forecasts."),
    r("aydinozcekic", "Aydin O.", "Best for an investor plan with a detailed financial model", "I will write a business plan with a detailed financial model", "5.0", "185", "125",
      "/aydinozcekic/do-your-business-plan-for-investors",
      "A Vetted Pro with a perfect rating across 185 reviews who writes business plans for investors with a detailed financial model."),
    r("mikelconsulting", "MikelConsulting", "Best for a bank loan business plan", "We will prepare a bank loan business plan", "5.0", "149", "100",
      "/mikelconsulting/prepare-a-professional-concise-and-modern-business-plan",
      "A Vetted Pro agency with a perfect rating across 149 reviews that prepares concise business plans for loan applications."),
    r("strategist_ceo", "Lucas W.", "Best for an SBA lender-ready plan", "I will prepare a lender-ready SBA 7a or 504 business plan", "5.0", "109", "1250",
      "/strategist_ceo/write-small-business-administration-sba-ready-business-plan",
      "A Vetted Pro with a perfect rating across 109 reviews who writes business plans for SBA loan applications.",
      "Premium pricing, starting near 1,250 dollars."),
    r("gerhardvanwyk", "Gerhard", "Best for a startup plan for investors or loans", "I will write your startup business plan for investors or loans", "5.0", "60", "100",
      "/gerhardvanwyk/write-your-startup-business-plan-for-investors-or-loan",
      "A Vetted Pro with a perfect rating who writes startup business plans aimed at investors or lenders."),
    r("mana007", "Osama M. Ashraf", "Best budget pick with the most reviews", "I will prepare a complete business plan", "4.9", "1000", "100",
      "/mana007/prepare-a-compete-business-plan",
      "A Vetted Pro with over a thousand reviews who prepares complete business plans, at a low starting price."),
], status="live")

add_picks.put("finance/financial-modeling", [
    r("financialplaner", "Ali Hassan", "Best overall for projections and forecasts", "I will provide investor-ready financial projections, forecasts and models", "5.0", "365", "100",
      "/financialplaner/prepare-financial-model-business-plan-bugdet-and-provide-bookkeeping-services",
      "A Vetted Pro with a perfect rating across 365 reviews who builds financial projections, forecasts and models."),
    r("elmehdinaffaa", "El Mehdi Naffaa", "Best for an Excel model with revenue projections", "I will build a certified Excel financial model, projections and business plan", "5.0", "142", "295",
      "/elmehdinaffaa/prepare-financial-plan-revenue-projections-sales-forecasting",
      "A Vetted Pro with a perfect rating across 142 reviews who builds Excel financial models with revenue and sales projections."),
    r("jamalkhan1112", "Jamal K", "Best for an investor-ready financial model", "I will create an investor-ready financial model or financial plan", "5.0", "79", "350",
      "/jamalkhan1112/create-professional-financial-model",
      "A Vetted Pro with a perfect rating who creates financial models and plans for investors."),
    r("mikelconsulting", "MikelConsulting", "Best for a financial forecast or plan", "We will prepare a financial forecast, projection or plan", "4.8", "208", "495",
      "/mikelconsulting/prepare-a-financial-plan-forecast-or-forecast",
      "A Vetted Pro agency with 208 reviews that prepares financial forecasts, projections and plans."),
    r("stevenleask", "Steven", "Best for a business plan paired with a model", "I will create a bespoke business plan and financial model", "4.8", "76", "110",
      "/stevenleask/business-planning-and-financial-forecasting",
      "A Vetted Pro with 76 reviews who builds a business plan together with a financial model and forecast, at a low starting price."),
], status="live")

add_picks.put("finance/bookkeeping", [
    r("learnshishir", "Shishir A.", "Best for QuickBooks Online or Xero bookkeeping", "I will be your bookkeeper using QuickBooks Online or Xero", "5.0", "243", "500",
      "/learnshishir/really-good-at-bookkeeping-on-qbo",
      "A Vetted Pro with a perfect rating across 243 reviews who does bookkeeping in QuickBooks Online and Xero.",
      "Starts at 500 dollars."),
    r("kareem_fr", "Fred Careem", "Best for monthly books and financial statements", "I will do monthly accounting and bookkeeping in QuickBooks Online", "5.0", "157", "110",
      "/kareem_fr/prepare-profit-and-loss-balance-sheet-financial-statements-and-bookkeeping",
      "A Vetted Pro with a perfect rating across 157 reviews who does monthly bookkeeping and prepares profit and loss and balance sheet statements."),
    r("btmurph013", "Beth Murphy", "Best for monthly QuickBooks reconciliation", "I will organize, bookkeep and reconcile your QuickBooks Online account", "5.0", "87", "250",
      "/btmurph013/reconcile-your-quickbooks-accounts-monthly",
      "A Vetted Pro with a perfect rating who organizes and reconciles QuickBooks Online accounts."),
    r("rakibulhasanacc", "Rakibul Hasan", "Best budget pick across QuickBooks, Xero and Wave", "I will do accurate QuickBooks bookkeeping and Xero accounting", "5.0", "80", "100",
      "/rakibulhasanacc/do-bookkeeping-on-quickbooks-online-xero-wave-with-excel",
      "A Vetted Pro with a perfect rating who does bookkeeping in QuickBooks, Xero and Wave, at a low starting price."),
    r("zfjharna", "Zannatul F", "Best for QuickBooks cleanup", "I will clean up your books in QuickBooks Online", "4.9", "174", "100",
      "/zfjharna/bookkeeper-accountant-for-cleanup-in-quickbooks-online",
      "A Vetted Pro with 174 reviews who cleans up messy books in QuickBooks Online."),
    r("muhammadkhan244", "Muhammad Khan", "Best for monthly reconciliation", "I will do monthly bookkeeping and reconciliation in QuickBooks Online", "4.9", "95", "120",
      "/muhammadkhan244/do-monthly-bookkeeping-in-quickbooks-online",
      "A Vetted Pro with 95 reviews who does monthly bookkeeping and reconciliation in QuickBooks Online."),
], status="live")

add_picks.put("finance/funding-pitch-presentations", [
    r("victorysamonova", "Victoria", "Best for premium pitch decks", "I will design premium pitch decks and business presentations", "5.0", "82", "350",
      "/victorysamonova/design-clean-and-professional-presentation",
      "A Vetted Pro with a perfect rating who designs pitch decks and business presentations."),
    r("ajpirela27", "Anderson P.", "Best for high-impact pitch decks with proven volume", "I will design an amazing PowerPoint pitch deck presentation", "4.9", "1000", "160",
      "/ajpirela27/design-and-elaborate-a-high-impact-powerpoint-template",
      "A Vetted Pro with over a thousand reviews who designs PowerPoint pitch decks."),
    r("mariawasim", "Aesthought", "Best for investor decks in PowerPoint or Google Slides", "I will design an investor pitch deck in PowerPoint or Google Slides", "4.9", "974", "150",
      "/mariawasim/design-creative-powerpoint-presentation",
      "A Vetted Pro with 974 reviews who designs investor pitch decks."),
    r("dexterlee138", "Dexter L", "Best for a premium investor deck", "I will design a premium PowerPoint pitch deck presentation", "4.9", "291", "280",
      "/dexterlee138/design-your-premium-powerpoint-presentation-and-pitch-deck",
      "A Vetted Pro with 291 reviews who designs premium PowerPoint pitch decks."),
    r("eastwestart", "Maria M", "Best for a pitch deck built in Figma", "I will design a pitch deck presentation in Figma", "4.9", "107", "200",
      "/eastwestart/design-a-professional-presentation",
      "A Vetted Pro with 107 reviews who designs pitch decks in Figma."),
    r("sramanaaiift", "Venkat", "Best for pitch decks and corporate slides", "I will design a pitch deck, business presentation and corporate slides", "4.9", "67", "190",
      "/sramanaaiift/design-business-powerpoint-presentations",
      "A Vetted Pro with 67 reviews who designs pitch decks, business presentations and corporate slides."),
], status="live")

add_picks.put("music-audio/sound-design", [
    r("hzsmith", "Mihu P.", "Best overall for game, app and film sound effects", "I will make sound design and sound effects for your game, animation or video", "5.0", "390", "220",
      "/hzsmith/produce-high-quality-sound-effects-for-your-apps-video-games-and-movies",
      "A Vetted Pro with a perfect rating across 390 reviews who makes sound effects for games, apps and movies."),
    r("markshwedow", "Mark S.", "Best budget pick for game and app sound", "I will create pro sound design and sound effects for your game or app", "5.0", "264", "100",
      "/markshwedow/create-catchy-sound-effects-for-your-video-game",
      "A Vetted Pro with a perfect rating across 264 reviews who creates sound effects for games and apps, at a low starting price."),
    r("nsmadsen", "Nathan M", "Best for custom sound effects", "I will make incredible sound effects and sound design", "5.0", "240", "125",
      "/nsmadsen/create-sound-effects-for-your-project",
      "A Vetted Pro with a perfect rating across 240 reviews who creates custom sound effects for projects."),
    r("gdh_digital", "Gordon Hookailo", "Best for sound design plus dialog cleanup and mixing", "I will sound design, clean dialog and mix your film or video", "5.0", "66", "125",
      "/gdh_digital/audio-edit-create-sound-effects-and-mix-your-video-or-audio-production",
      "A Vetted Pro with a perfect rating who creates sound effects, cleans dialog and mixes video and film audio."),
    r("gvalerioaz", "Goncalo Valerio", "Best for ads and film sound design", "I will craft premium sound design for commercials, ads and film", "5.0", "53", "180",
      "/gvalerioaz/do-sound-design-for-your-movie-game-ad",
      "A Vetted Pro with a perfect rating who does sound design for commercials, ads and film."),
    r("forlai_audio", "Antonio A", "Best for games and videos", "I will do pro sound design and sound effects for any game or video", "4.9", "56", "220",
      "/forlai_audio/add-to-your-project-a-unique-sound-future-is-here",
      "A Vetted Pro who does sound design and sound effects for games and videos."),
], status="live")

add_picks.put("music-audio/vocal-tuning", [
    r("oriabrian", "Oria Brian", "Best overall for tuning, mixing and mastering", "I will tune, mix and master your song, album or vocal", "5.0", "246", "130",
      "/oriabrian/add-instruments-mix-and-master-your-song",
      "A Vetted Pro with a perfect rating across 246 reviews who tunes, mixes and masters songs and vocals."),
    r("mubthemusichub", "Walter Nuzzo", "Best for processing and editing vocals", "I will professionally process, edit and mix your vocals", "5.0", "74", "100",
      "/mubthemusichub/professionally-mix-and-master-your-vocals",
      "A Vetted Pro with a perfect rating who processes, edits and mixes vocals, at a low starting price."),
    r("brendanruane", "Brendan R", "Best for a fast vocal mix", "I will mix your vocals in 24 hours", "5.0", "67", "100",
      "/brendanruane/mix-your-vocals-in-24-hours",
      "A Vetted Pro with a perfect rating who mixes vocals quickly."),
    r("callyofficial", "Cally", "Best for tuning and mixing vocals", "I will professionally tune and mix your vocals", "4.9", "357", "100",
      "/callyofficial/enhance-your-vocals-and-bring-the-best-out-of-your-voice",
      "A Vetted Pro with 357 reviews who tunes and mixes vocals, at a low starting price."),
], status="live")

add_picks.put("programming-tech/custom-websites", [
    r("ahsanalikhan181", "Ahsaan Ali Khan", "Best overall for a full custom website", "I will build a custom website as a full stack developer", "5.0", "442", "180",
      "/ahsanalikhan181/design-and-develop-a-complete-website",
      "A Vetted Pro with a perfect rating across 442 reviews who builds complete custom websites as a full stack developer."),
    r("shahab01", "Codecapital", "Best for responsive custom builds", "We will build a responsive website with custom development", "5.0", "382", "250",
      "/shahab01/do-web-programing-responsive-website-fix-web-related-error",
      "A Vetted Pro agency with a perfect rating across 382 reviews that builds responsive websites and fixes web errors."),
    r("ahmad_rafiq", "Codexia Tech", "Best budget pick for custom code", "We will do custom website development as full stack developers", "5.0", "174", "100",
      "/ahmad_rafiq/write-or-fix-any-code",
      "A Vetted Pro agency with a perfect rating across 174 reviews that writes and fixes web code, at a low starting price."),
    r("gisdataanalysis", "DevioTech", "Best for Laravel development", "We will do custom website development using Laravel", "5.0", "126", "900",
      "/gisdataanalysis/do-web-development-using-laravel",
      "A Vetted Pro agency with a perfect rating across 126 reviews that builds websites with Laravel.",
      "Starts at 900 dollars."),
    r("shreyanshsin261", "Shreyansh Singh", "Best for SaaS and front-end builds", "I will be your full stack web developer for SaaS, apps and custom websites", "5.0", "86", "100",
      "/shreyanshsin261/be-full-stack-web-developer-for-saas-app-frontend-custom-website-development",
      "A Vetted Pro with a perfect rating who builds SaaS apps, front ends and custom websites."),
    r("junii007", "Junaid Rashid", "Best for custom builds and bug fixes", "I will do custom website development as a full stack developer", "4.9", "214", "100",
      "/junii007/can-fix-your-bugs-in-no-time-related-to-web-programming",
      "A Vetted Pro with 214 reviews who does custom website development and fixes web bugs."),
], status="live")

add_picks.put("programming-tech/game-development", [
    r("keshavdeveloper", "Keshav Infotech", "Best overall for Unity 2D and 3D games", "We will do Unity game development and mobile game development", "5.0", "976", "200",
      "/keshavdeveloper/develop-unity-2d-and-3d-game",
      "A Vetted Pro agency with a perfect rating across 976 reviews that develops Unity 2D and 3D games."),
    r("rakibj45", "Gameloops", "Best budget pick for Unity games on mobile and PC", "We will design and develop games in Unity for mobile, PC and more", "5.0", "68", "100",
      "/rakibj45/do-unity-game-development",
      "A Vetted Pro agency with a perfect rating that develops Unity games for mobile and PC, at a low starting price."),
    r("chronos_1", "Romin V", "Best for 2D and 3D Unity games", "I will develop 2D and 3D games in Unity for mobile, web and PC", "5.0", "58", "1250",
      "/chronos_1/create-a-game-in-unity-for-you",
      "A Vetted Pro with a perfect rating who develops 2D and 3D Unity games for mobile, web and PC.",
      "Premium pricing, starting near 1,250 dollars."),
    r("ngengames", "AptechMedia", "Best for Unity 3D or Unreal Engine games", "We will do high-quality Unity 3D or Unreal Engine games", "4.9", "192", "500",
      "/ngengames/make-games-apps-websites-2d-designs-for-you",
      "A Vetted Pro agency with 192 reviews that builds Unity 3D and Unreal Engine games."),
    r("everythingunity", "Eunity", "Best for Unity scripts and cross-platform games", "I will develop your Unity game or app for any platform", "4.9", "102", "260",
      "/everythingunity/create-any-unity-c-sharp-script-for-you",
      "A Vetted Pro with 102 reviews who develops Unity games and apps and writes custom C# scripts."),
    r("dingaloo", "Collin Ossman", "Best for a 2D Unity game", "I will create a 2D game for you in the Unity engine", "4.9", "83", "295",
      "/dingaloo/create-a-2d-game-for-you-in-the-unity-engine",
      "A Vetted Pro with 83 reviews who creates 2D games in Unity."),
], status="live")
