import add_picks
add_picks.CHECKED = "2026-10-03"
add_picks.put("graphics-design/book-covers", [
    dict(user="weirdwiring", name="Matteo G.", best_for="Best overall for a minimalist, vector-style cover",
         title="I will design a minimalist book cover", rating="5.0", reviews="85", level="Vetted Pro", price="160",
         url="/weirdwiring/create-a-vector-art-book-cover-design",
         why="A Vetted Pro with a perfect rating who designs clean, minimalist covers. Every package comes with unlimited revisions and a 3D mockup, and the larger ones add back and spine, hardback and audiobook versions.",
         watch_out="Delivery runs from 5 to 14 days depending on the package, so allow time before a launch date."),
    dict(user="pwaperpro", name="Stefan P.", best_for="Most proven cover designer, best value",
         title="I will design a captivating book cover that sells", rating="4.9", reviews="818", level="Vetted Pro", price="130",
         url="/pwaperpro/design-a-captivating-book-cover-design-that-sells",
         why="A Vetted Pro with more than 800 reviews. Even the entry package includes source files and a 3D mockup, with delivery in two days, and the top package adds a second concept, an audiobook cover and a video animation.",
         watch_out="The entry package covers only the front cover; back and spine design starts in the middle package."),
    dict(user="designer119", name="Priyantha D", best_for="Best for ebook and Kindle publishing",
         title="I will create a unique book cover, ebook cover and KDP cover", rating="4.9", reviews="388", level="Vetted Pro", price="185",
         url="/designer119/design-professional-book-cover",
         why="A Vetted Pro with almost 400 reviews who designs ebook and print covers. Source files and a 3D mockup are included, each package is delivered in three days, and the larger ones add a back cover, two concepts and a barcode.",
         watch_out="Two design concepts only start in the middle package, and revisions are capped at three or four."),
    dict(user="marmarko78", name="Marko M.", best_for="Best for premium print and dust-jacket projects",
         title="I will do a unique book cover design for ebook, paperback, hardcover and dust jacket", rating="4.9", reviews="156", level="Vetted Pro", price="600",
         url="/marmarko78/do-a-unique-book-cover-design",
         why="A Vetted Pro offering custom graphics and typography for ebook, paperback, hardcover and dust-jacket covers, with unlimited revisions, source files, a social media kit and a mockup in every package.",
         watch_out="High-end pricing from 600 dollars, with the top package at 1,700 dollars and three weeks of delivery."),
    dict(user="predra6", name="Predrag M.", best_for="Best for a full print-ready package",
         title="I will design your professional eye catching book cover", rating="4.9", reviews="136", level="Vetted Pro", price="380",
         url="/predra6/design-you-a-perfect-book-cover-6017",
         why="A Vetted Pro whose packages offer two concepts, a print-ready full wrap for paperback or hardcover, source files, a social media kit and a mockup, with a premium option that adds book promotion materials.",
         watch_out="Print-ready files start in the middle package and take about ten days to deliver."),
    dict(user="davidcolonfilm", name="David", best_for="Best for covers with licensed stock imagery",
         title="I will help you design your book cover or ebook", rating="4.8", reviews="410", level="Vetted Pro", price="240",
         url="/davidcolonfilm/help-you-design-your-book-cover-or-ebook",
         why="A Vetted Pro with more than 400 reviews. Each package includes licensed stock images, image adjustments, source files and a 3D mockup, and the middle and top packages add a print cover.",
         watch_out="Delivery takes six days in every package, and revisions are capped at two to four."),
], status="live")
