import add_picks
add_picks.CHECKED = "2026-10-03"
add_picks.put("writing-translation/cover-letters", [
    dict(user="adamhalpert", name="Adam H", best_for="Best for MBA and graduate applications",
         title="I will edit and improve your resume or cover letter to MBA quality", rating="4.9", reviews="43", level="Vetted Pro", price="350",
         url="/adamhalpert/edit-and-improve-your-resume-or-cover-letter-up-to-mba-quality",
         why="A Vetted Pro who edits and rewrites cover letters and resumes, with packages that cover one document, several documents for a job or university application, or a full A-to-Z service with interview and networking support.",
         watch_out="Premium pricing from 350 dollars and a seven-day delivery time even for the smallest package."),
    dict(user="amandaaspey", name="Amanda A.", best_for="Best overall for a polished, job-specific letter",
         title="I will write your successful cover letter", rating="4.9", reviews="42", level="Vetted Pro", price="100",
         url="/amandaaspey/create-a-cover-letter-to-land-you-that-job-3447",
         why="A Vetted Pro who writes a tailored cover letter with applicant-tracking-friendly formatting, delivered in two days with unlimited revisions. Packages differ only by letter length, from one to three pages.",
         watch_out="Each package covers a single targeted letter, so applying to several roles means several orders."),
    dict(user="franzitronnier", name="Franzy", best_for="Best for English or German applications",
         title="I will create your cover letter in English or German", rating="5.0", reviews="268", level="Level 1", price="35",
         url="/franzitronnier/create-your-cover-letter-in-engish-or-german",
         why="A perfect 5.0 rating across 268 reviews. Writes a new cover letter from your current documents, with options for a translated version or both English and German in one order, and two revisions in every package.",
         watch_out="The basic package does not include translation; pick a higher one if you need the second language."),
    dict(user="principalmike", name="Mike", best_for="Most reviewed seller, flexible letter writing",
         title="I will write any kind of letter or email", rating="4.9", reviews="1000", level="Top Rated", price="40",
         url="/principalmike/write-a-great-letter-for-you",
         why="A Top Rated seller with more than a thousand reviews who writes letters, emails and short documents, priced by length from 400 words up to 1,000 words, with two revisions in each package.",
         watch_out="This is a general letter-writing service rather than a cover-letter specialist, so share the job post and your background clearly."),
    dict(user="jmahlfeldt", name="Julie M.", best_for="Best budget pick for editing a letter you already have",
         title="I will write your professional cover letter", rating="4.9", reviews="327", level="Level 1", price="15",
         url="/jmahlfeldt/write-your-personalized-cover-letter",
         why="A well-reviewed seller with a low entry price. You can have an existing letter reviewed and edited, or have a new one written from your resume and the job description, with a three-letter package for multiple applications.",
         watch_out="Delivery is seven days in every package and the new-letter packages include only one revision."),
    dict(user="lambertcv", name="Richard Lambert", best_for="Best for a general-purpose letter from scratch",
         title="I will write your professional cover letter from scratch", rating="4.8", reviews="360", level="Top Rated", price="55",
         url="/lambertcv/write-your-professional-cover-letter-to-get-you-noticed",
         why="A Top Rated seller who writes a full cover letter from scratch, either tailored to a specific position or as a general letter you can reuse, delivered in three days with unlimited revisions.",
         watch_out="One flat package with no add-ons, so extras such as a resume are not part of this listing."),
], status="live")
