import add_picks
add_picks.CHECKED = "2026-10-03"
add_picks.put("video-animation/animated-explainers", [
    dict(user="bogdanzah", name="Bogdan", best_for="Best overall for software and app explainers",
         title="I will create a custom 2D animated explainer video", rating="5.0", reviews="1000", level="Vetted Pro", price="400",
         url="/bogdanzah/create-a-cool-and-professional-whiteboard-video-for-your-success-ideas-in-24-hrs",
         why="A Vetted Pro with a perfect rating across more than a thousand reviews. Packages include a storyboard, script writing, characters, voice-over and subtitles, and the entry package is aimed at software and app demos.",
         watch_out="Delivery is ten days in every package and the price covers a 30-second video, so longer videos need a custom quote."),
    dict(user="explain_animate", name="Kirsty N", best_for="Best for conversion-focused brand explainers",
         title="I will create a high converting animated explainer video", rating="5.0", reviews="200", level="Vetted Pro", price="445",
         url="/explain_animate/create-a-custom-2d-animation-or-cartoon-explainer-video-f3ae7d26-5ef3-4c01-aa82-eb73333de1d7",
         why="A Vetted Pro with a perfect 5.0 across 200 reviews. Packages scale by length, from 30 to 90 seconds, and include script, storyboard, voice-over, custom characters and subtitles, with a strategy element in the top package.",
         watch_out="Only one to three revisions per package, so lock down the script before animation begins."),
    dict(user="khan_16", name="Khuram", best_for="Best for short, handcrafted animations",
         title="I will create a custom 2D animated explainer video", rating="4.9", reviews="1000", level="Vetted Pro", price="150",
         url="/khan_16/create-2d-animated-video",
         why="A Vetted Pro with more than a thousand reviews who offers handcrafted animation with unlimited revisions, branding, voice-over, music and HD output. Packages are priced by running time, from 10 to 90 seconds.",
         watch_out="Pricing climbs steeply with length: the entry package covers only 10 seconds, and the 60-second package is 900 dollars."),
    dict(user="animaester", name="Abdullah", best_for="Best for all-inclusive 2D explainers",
         title="I will create the best 2D animated explainer video", rating="4.9", reviews="693", level="Vetted Pro", price="325",
         url="/animaester/create-2d-animation-with-eye-catching-graphics",
         why="A Vetted Pro with nearly 700 reviews. Every package includes script, voice-over and full HD output with unlimited revisions, in tiers of up to 30, 60 or 90 seconds.",
         watch_out="Delivery takes 10 to 21 days depending on length, so plan well ahead of a launch."),
    dict(user="albertanimation", name="Albert And Team", best_for="Best budget pick for a short animated video",
         title="I will create custom modern 2D animation explainer videos", rating="4.8", reviews="804", level="Vetted Pro", price="150",
         url="/albertanimation/create-custom-explainer-video-animation-custom-explainer-video-animation",
         why="A Vetted Pro team with more than 800 reviews and the lowest entry price in this list. Packages cover 15, 30 or 60 seconds with script, storyboard, voice-over and subtitles, and the larger two have unlimited revisions.",
         watch_out="The 15-second entry package is very short and includes only three revisions."),
    dict(user="addictiongfx", name="AGFX Studio", best_for="Best for detailed illustrations and icon animation",
         title="I will produce high quality animated explainer videos", rating="4.8", reviews="292", level="Vetted Pro", price="250",
         url="/addictiongfx/produce-high-quality-animated-explainer-videos",
         why="A Vetted Pro studio with almost 300 reviews. Packages run from a simple flat-graphics 30-second video to a 60-second piece with detailed illustrations, icons and complex transitions.",
         watch_out="Delivery can take up to 30 days and orders are by request, so ask about timing before you commit."),
], status="live")
