import add_picks
add_picks.CHECKED = "2026-10-03"
add_picks.put("writing-translation/linkedin-profiles", [
    dict(user="williambryan392", name="Will Bryant", best_for="Best overall for a full strategic rewrite",
         title="I will optimize your LinkedIn profile", rating="5.0", reviews="129", level="Vetted Pro", price="575",
         url="/williambryan392/linkedin-profile-optimization-writer",
         why="A Vetted Pro with a perfect rating across 129 reviews. The work starts with a strategy video call, then the seller optimizes every section of your profile directly, with two revisions included.",
         watch_out="The seller logs in to your account to make the changes, so change your password afterwards."),
    dict(user="bigtechresume", name="Emily P", best_for="Best for senior and executive profiles",
         title="I will transform your LinkedIn profile to stand out", rating="5.0", reviews="34", level="Vetted Pro", price="1000",
         url="/bigtechresume/transform-your-linkedin-profile-to-stand-out",
         why="A Vetted Pro with a perfect rating. Packages cover headline, summary, experience, skills and keywords, ranging from a written review in a shared document to a full makeover with direct updates, unlimited revisions and 1:1 sessions.",
         watch_out="Premium pricing, from about 1,000 dollars, and up to 30 days of delivery; a better fit for senior roles than a quick refresh."),
    dict(user="wizkidvideo", name="Colette Barry", best_for="Best budget pick with a long track record",
         title="I will create, optimize and manage your LinkedIn profile", rating="4.9", reviews="594", level="Level 2", price="30",
         url="/wizkidvideo/create-optimize-and-manage-linkedin-profile-26c7",
         why="Nearly 600 reviews at a 4.9 rating. The entry package delivers a profile rewrite in a document within two days, with unlimited revisions, and the middle package updates the profile directly.",
         watch_out="The top package adds ongoing posting and connection activity; decide whether you want that before choosing it."),
    dict(user="glenna_hayes", name="Glenna H", best_for="Best for a profile plus company page",
         title="I will upgrade and optimize your LinkedIn profile and business page", rating="4.9", reviews="392", level="Level 2", price="15",
         url="/glenna_hayes/create-upgrade-revamp-and-optimize-your-linkedin-profile-and-business-page",
         why="A Level 2 seller with close to 400 reviews. Packages range from a rewritten headline and bio up to a full profile optimization with a banner and setup guidelines, with unlimited revisions and two-day delivery.",
         watch_out="Prices are very low, so check the package list carefully to see exactly what each tier covers."),
    dict(user="karenroz", name="Karen Roziner", best_for="Best for a done-for-you rewrite",
         title="I will provide a complete LinkedIn profile optimization", rating="4.9", reviews="165", level="Top Rated", price="150",
         url="/karenroz/write-and-optimize-your-linkedin-profile",
         why="A Top Rated seller who writes every section of your profile, with a cover photo image included and unlimited revisions. A middle package updates the profile for you, and the top package adds a strategy call.",
         watch_out="Starts at 150 dollars, and the strategy call is only in the top package."),
    dict(user="jennamatthews12", name="Jenna", best_for="Best for a document-only rewrite",
         title="I will upgrade and optimize your LinkedIn profile", rating="4.9", reviews="116", level="Top Rated", price="30",
         url="/jennamatthews12/upgrade-and-optimize-your-linkedin-profile",
         why="A Top Rated seller with more than 9,000 completed orders in total. You can buy just the About section, a full optimization document, or a complete upgrade done in your account, all delivered in three days.",
         watch_out="Only two revisions per package, and the full upgrade needs access to your account."),
], status="live")
