import add_picks
add_picks.CHECKED = "2026-10-03"
add_picks.put("writing-translation/product-descriptions", [
    dict(user="twocakes", name="Demi", best_for="Best overall for online store product pages",
         title="I will be your Shopify product description writer to boost sales", rating="5.0", reviews="1000", level="Vetted Pro", price="150",
         url="/twocakes/write-a-unique-product-description",
         why="A Vetted Pro with a perfect rating across more than a thousand reviews. Each product gets a title, five bullet points and a short description, and the middle and top packages add SEO keywords, with bundles of five or ten products.",
         watch_out="Packages start at five products and include only one revision, so send your keywords and product details up front."),
    dict(user="carrieblogger", name="Carrie French", best_for="Best for in-depth marketplace listings",
         title="I will write a competitive Amazon listing that is optimized to sell", rating="5.0", reviews="116", level="Vetted Pro", price="200",
         url="/carrieblogger/write-competitive-amazon-listings",
         why="A Vetted Pro with a perfect rating who writes marketplace listings backed by competitor research, from a bullet-points-only package to a full listing with three title options and a longer description for enhanced brand content.",
         watch_out="Premium pricing from 200 dollars and seven-day delivery in every package."),
    dict(user="rorywritesuk", name="Rory M", best_for="Best for A+ brand content",
         title="I will write sales spiking Amazon A+ content", rating="4.8", reviews="106", level="Vetted Pro", price="95",
         url="/rorywritesuk/a-sales-spiking-ebc-a-plus-amazon-product-listing-description",
         why="A Vetted Pro who writes enhanced brand content with competitor analysis and unlimited revisions. The middle package adds the title, bullets and keyword research, and the top package adds image and infographic design.",
         watch_out="Delivery takes ten days in every package, and the entry package covers the A+ copy only, with no images."),
    dict(user="alexvlaston", name="Alex Vlaston", best_for="Best budget pick for a full listing",
         title="I will write top Amazon listing SEO product descriptions", rating="4.9", reviews="1000", level="Top Rated", price="25",
         url="/alexvlaston/write-the-mother-of-amazon-product-descriptions",
         why="A Top Rated seller with more than a thousand reviews. Packages include a title, five bullets, description and SEO keywords, with delivery in one or two days and unlimited revisions, and the larger ones add A+ text.",
         watch_out="The cheapest package is a short 250-word listing; choose the middle package for a full listing."),
    dict(user="ssj1236", name="Subhan S.", best_for="Best for keyword-driven listings",
         title="I will provide Amazon listing optimization that will boost sales", rating="4.9", reviews="1000", level="Top Rated", price="40",
         url="/ssj1236/write-amazon-listing-and-description",
         why="A Top Rated seller with more than a thousand reviews who writes SEO titles, bullets and descriptions with unlimited revisions. Upper packages add keyword lists, ad keywords and a video consultation.",
         watch_out="Built around Amazon listings, so it is a weaker fit for other store platforms."),
    dict(user="fastadking", name="Kevin N.", best_for="Best for HTML-ready listing copy",
         title="I will write your Amazon product listing that sells", rating="4.9", reviews="1000", level="Top Rated", price="45",
         url="/fastadking/write-your-amazon-listing-that-sells",
         why="A Top Rated seller with more than a thousand reviews who delivers a title, five bullets and description with competitor research and keywords in three days. The middle package adds HTML formatting and a backend keyword file.",
         watch_out="Two revisions per package, so give clear brand and product notes before you start."),
], status="live")
