from add_picks import put
put("writing-translation/resume-writing", [
    dict(user="alexlouiserose", name="Alex Rose", best_for="Best overall, written by a former recruiter",
         title="I will write your resume using my recruiting expertise", rating="5.0", reviews="1513", level="Vetted Pro", price="180",
         url="/alexlouiserose/use-my-xp-as-a-startup-tech-recruiter-to-review-your-resume",
         why="A former tech recruiter with a perfect rating across more than 1,500 reviews who reviews, edits and rewrites your resume from a hiring manager's point of view, with unlimited revisions and an optional cover letter and LinkedIn update.",
         watch_out="Especially strong for tech and startup roles; mention your target industry if it is different."),
    dict(user="lambertcv", name="Richard Lambert", best_for="Best for a fast, ATS-friendly resume",
         title="I will deliver a 12 hour professional resume writing service", rating="4.9", reviews="2734", level="Vetted Pro", price="130",
         url="/lambertcv/deliver-the-full-cv-service-in-12-hours",
         why="A US-based resume writer with tens of thousands of completed orders who delivers an ATS-optimized resume with a free cover letter within a day, plus LinkedIn and interview prep in the higher package. Unlimited revisions.",
         watch_out="Very fast turnaround; set aside time to answer the questionnaire properly so the writing reflects your real achievements."),
    dict(user="bcpatchesco", name="Cameron G", best_for="Best for resume plus salary negotiation help",
         title="I will deliver a 24 hour professional resume writing service", rating="4.9", reviews="766", level="Vetted Pro", price="125",
         url="/bcpatchesco/deliver-a-24-hour-professional-resume-writing-service",
         why="Edits and rewrites your resume for applicant tracking systems in 24 hours, adding a free cover letter and a salary negotiation guide, with LinkedIn optimization in the higher package and unlimited revisions.",
         watch_out="Fast delivery depends on you sending complete information; paid consultations are extra."),
    dict(user="cvmaestro2016", name="Renzo M.", best_for="Best for directors and C-level executives",
         title="I will deliver a fully customized executive resume that positions you for top roles", rating="4.9", reviews="247", level="Vetted Pro", price="395",
         url="/cvmaestro2016/offer-resume-and-linkedin-solutions-for-c-level-executives",
         why="Writes customized resumes and LinkedIn profiles for senior leaders, directors and C-suite executives, with an executive cover letter in the higher package and unlimited revisions.",
         watch_out="Priced for senior roles; overkill for early-career resumes."),
    dict(user="bigtechresume", name="Emily P", best_for="Best for big tech career moves",
         title="I will transform your resume and cover letter, plus linkedin", rating="4.9", reviews="86", level="Vetted Pro", price="900",
         url="/bigtechresume/write-your-way-to-a-big-tech-job-via-resume",
         why="A premium service focused on big tech roles, from an in-depth review with tailored recommendations to a full rewrite with unlimited revisions and one-to-one sessions.",
         watch_out="The highest price among the picks; the basic package is a review with recommendations rather than a rewrite."),
    dict(user="ktrimble39", name="Kristina", best_for="Best budget pick for a clean resume",
         title="I will write a fully optimized professional resume and cover letter", rating="4.9", reviews="1989", level="Top Rated", price="60",
         url="/ktrimble39/write-a-professional-resume-and-cover-letter",
         why="A US-based Top Rated writer with thousands of completed orders who writes ready-to-send one or two-page resumes, with a cover letter in the middle package and unlimited revisions.",
         watch_out="Delivery takes about five days."),
], status="live")
