import add_picks
add_picks.CHECKED = "2026-10-03"
add_picks.put("graphics-design/thumbnails-design", [
    dict(user="pookiezz", name="Lior", best_for="Best overall for cinematic, photo-based thumbnails",
         title="I will create professional cinematic youtube thumbnails for you", rating="5.0", reviews="982", level="Top Rated", price="15",
         url="/pookiezz/create-youtube-thumbnails-for-you",
         why="A Top Rated designer with a perfect rating across nearly 1,000 reviews who creates polished, cinematic thumbnails from your footage and photos, with unlimited revisions and two or three versions for split testing in the higher packages.",
         watch_out="Works with photos and editing only, not drawn characters; choose an illustrator for cartoon styles."),
    dict(user="marisesekiban", name="Marise Sekiban", best_for="Best for hand-drawn, illustrated thumbnails",
         title="I will draw thumbnails for your videos as you want", rating="5.0", reviews="564", level="Level 2", price="20",
         url="/marisesekiban/draw-thumbnails-for-your-videos",
         why="Draws custom illustrated thumbnails of a scene from your video, from a single colored character up to three characters with a detailed background, delivered in two days.",
         watch_out="Send a clip or screenshot of the moment and reference photos of any real people; extra characters cost more."),
    dict(user="thumbnails_ayan", name="Ayan", best_for="Best for channels that need thumbnails in bulk",
         title="I will make youtube thumbnail from pov of a CTR boosting expert", rating="4.9", reviews="20224", level="Level 2", price="10",
         url="/thumbnails_ayan/make-view-boosting-youtube-thumbnail-in-5hrs",
         why="One of the most reviewed thumbnail designers, with more than 20,000 reviews, offering single thumbnails or packs of five and ten for different videos, with unlimited revisions and title suggestions in the largest pack.",
         watch_out="Click-through results vary by channel and niche, so judge the designs rather than the promised numbers; the queue can be long."),
    dict(user="sagorlbk2014", name="Sagor", best_for="Best budget pick for regular uploads",
         title="I will design high CTR youtube thumbnails that get more clicks", rating="4.9", reviews="10539", level="Level 2", price="10",
         url="/sagorlbk2014/design-2-professional-amazing-youtube-thumbnail-in-2hr",
         why="A very experienced thumbnail designer with more than 10,000 reviews and low starting prices, with image sourcing included, unlimited revisions and packs of five or ten thumbnails.",
         watch_out="Often has many orders in queue, so allow time if your upload date is fixed."),
    dict(user="itsmohitchouhan", name="Ravi K", best_for="Best for consistent branding with source files",
         title="I will design catchy youtube thumbnail", rating="4.9", reviews="7924", level="Top Rated", price="15",
         url="/itsmohitchouhan/design-catchy-youtube-thumbnail",
         why="A Top Rated designer with nearly 8,000 reviews who includes the editable source file in every package, which makes it easy to keep a consistent style across a series, with unlimited revisions.",
         watch_out="The largest package of ten branded thumbnails is a big step up in price from the single-thumbnail options."),
    dict(user="art_imperio", name="Neo", best_for="Best for cartoon and gaming-style thumbnails",
         title="I will draw cartoon youtube thumbnail in any style", rating="4.9", reviews="5483", level="Top Rated", price="20",
         url="/art_imperio/draw-cartoon-youtube-thumbnail-in-any-style",
         why="A Top Rated illustrator who draws custom thumbnails in cartoon, anime, comic, semi-realistic and game-inspired styles, with up to five characters and detailed backgrounds, delivered in a day.",
         watch_out="Two revisions per package; avoid asking for copyrighted characters you do not have rights to use."),
], status="live")
