import add_picks
add_picks.CHECKED = "2026-10-04"
add_picks.put("business/virtual-assistant", [
    dict(user="razashah158", name="FBA Venture", best_for="Best for an Amazon store assistant",
         title="I will be your Amazon FBA virtual assistant for private label", rating="5.0", reviews="125", level="Vetted Pro", price="100",
         url="/razashah158/amazon-virtual-assistant-amazon-fba-amazon-fba-virtual-assistant-amazon-store-va",
         why="A Vetted Pro with a perfect rating across 125 reviews who specializes in Amazon store support. Packages cover inventory, orders, customer messages, promotions and reporting, from a starter account audit to a 30-day plan for up to three products.",
         watch_out="Specialized in Amazon sellers, so a poor fit if you need general office or personal assistant help."),
    dict(user="lauraolmos769", name="Laura Olmos", best_for="Best for marketing and content tasks",
         title="I will be your creative virtual assistant and marketing specialist", rating="5.0", reviews="89", level="Vetted Pro", price="150",
         url="/lauraolmos769/provide-virtual-assistant-services",
         why="A Vetted Pro with a perfect rating who handles social media, ads, newsletter and blog tasks as a virtual assistant. Offers a fixed-price task package as well as hourly work.",
         watch_out="The fixed package is a single task with a 30-day delivery window, so agree on scope before ordering."),
    dict(user="reza_asif", name="Asif Reza", best_for="Best budget pick for general admin work",
         title="I will be your administrative virtual assistant", rating="5.0", reviews="63", level="Vetted Pro", price="100",
         url="/reza_asif/be-your-administrative-virtual-assistant",
         why="A Vetted Pro with a perfect rating who sells time in blocks of 10, 25 or 50 hours for administrative support, data entry, web research and spreadsheet formatting, at a low hourly rate.",
         watch_out="Priced by hours, not by outcome, so describe the tasks and expected output clearly to avoid running over."),
    dict(user="mohammadjalil", name="Jalil", best_for="Best for hands-on Amazon account management",
         title="I will be your Amazon virtual assistant, FBA consultant and PPC expert", rating="4.9", reviews="61", level="Vetted Pro", price="150",
         url="/mohammadjalil/be-your-amazon-fba-virtual-assistant",
         why="A Vetted Pro offering Amazon account management and consulting for 7, 14 or 30 days, covering inventory, orders, customer assistance, promotions and reporting, with an audit and coaching in the top package.",
         watch_out="Sold as a time-limited engagement; the 30-day package takes the full month, so plan the timing."),
    dict(user="angiesolutions", name="Angie Quintero", best_for="Best for ongoing executive admin support",
         title="I will be your reliable executive assistant for admin and personal support", rating="4.9", reviews="53", level="Vetted Pro", price="150",
         url="/angiesolutions/be-your-customer-service-assistant",
         why="A Vetted Pro who handles email, scheduling, data entry and follow-ups, with packages that grow from quick admin help to full admin management over 30 days. Hourly work is also available.",
         watch_out="Delivery windows are long, from 7 to 30 days, so it suits ongoing support more than urgent tasks."),
    dict(user="kinshasia17", name="Kinshasia J", best_for="Best for short, focused executive support",
         title="I will be your efficient virtual executive assistant", rating="4.8", reviews="187", level="Vetted Pro", price="120",
         url="/kinshasia17/be-your-reliable-virtual-assistant",
         why="A Vetted Pro with close to 190 reviews who sells focused blocks of two, five or ten hours to manage priorities and improve workflow, with hourly work available too.",
         watch_out="One of the higher hourly rates in this list, so it fits specific, well-defined tasks better than routine busywork."),
], status="live")
