import add_picks
add_picks.CHECKED = "2026-10-03"
add_picks.put("programming-tech/wix", [
    dict(user="haileycopy", name="Shani", best_for="Best overall for small business Wix sites",
         title="I will do wix website design and wix website redesign", rating="5.0", reviews="89", level="Vetted Pro", price="100",
         url="/haileycopy/design-and-develop-a-wix-website-or-wix-website-redesign-for-your-business",
         why="A Vetted Pro with a perfect rating who designs and redesigns Wix sites for small businesses, from a three-section landing page up to a ten-page site with online store and booking setup, built to be mobile friendly and search friendly.",
         watch_out="Revisions are limited in the smaller packages, so send your content and examples before work starts."),
    dict(user="abdulrehman092", name="Abdul Rehman", best_for="Best for a Wix online store",
         title="I will create wix website design redesign or wix online store", rating="5.0", reviews="79", level="Vetted Pro", price="100",
         url="/abdulrehman092/create-wix-website-design-redesign-or-wix-online-store",
         why="A Vetted Pro who builds Wix and Wix Studio sites and online stores, with product setup and payment integration included and unlimited revisions in every package.",
         watch_out="Asks buyers to message before ordering; product setup covers ten products, so larger catalogs need a custom quote."),
    dict(user="namrata1196", name="Namrata P", best_for="Best for a custom-designed Wix Studio site",
         title="I will create your responsive wix studio or wix website", rating="5.0", reviews="53", level="Vetted Pro", price="310",
         url="/namrata1196/create-wix-editorx-websites",
         why="A UX and UI designer with years of Wix experience who builds fully custom Wix Studio sites optimized for every screen size, focused on clear structure and conversions rather than templates.",
         watch_out="Premium pricing and longer delivery, up to 30 days for multi-page sites."),
    dict(user="csmarketingllc", name="Chris S", best_for="Most proven Wix designer",
         title="I will build your professional wix website with unlimited revisions", rating="4.9", reviews="889", level="Vetted Pro", price="295",
         url="/csmarketingllc/design-develop-or-redesign-a-wix-website",
         why="A US-based Vetted Pro with nearly 900 reviews who designs custom Wix sites without templates, with basic SEO, speed optimization and online store setup included, and unlimited revisions in the larger packages.",
         watch_out="Delivery is around two weeks even for one page; plan ahead if you have a launch date."),
    dict(user="ambreenfalah", name="Falah A.", best_for="Best for a quick coming-soon page or redesign",
         title="I will build, design, or redesign your professional wix website", rating="4.9", reviews="454", level="Vetted Pro", price="150",
         url="/ambreenfalah/design-or-redesign-wix-weebly-or-squarespace-website",
         why="A Vetted Pro with more than ten years of Wix experience, offering everything from a fast coming-soon page with a signup form to full redesigns and online stores, with unlimited revisions in every package.",
         watch_out="The entry package is a single coming-soon page; full multi-page sites start in the middle package."),
    dict(user="uimuse", name="UiMuse", best_for="Best for animated, modern business sites",
         title="I will design a high converting wix website and wix website redesign wix online store", rating="4.9", reviews="167", level="Vetted Pro", price="195",
         url="/uimuse/design-a-high-converting-wix-website-and-wix-website-redesign",
         why="A Vetted Pro and certified Wix partner who designs modern business sites with interactive animations, and adds online store features and an SEO-ready structure in the largest package.",
         watch_out="Only one revision in the landing page package; choose a larger package if you expect several rounds of changes."),
], status="live")
